MP表示を経験値barに移行
TheSkyBlock/TheSkyBlock pull request #127
Opened 2021-02-06 11:04 UTC by kaputina

オバフロ二分探索はわからなかったので採用できませんでした・・・
datapack_versionが上がっています

2021-02-06 11:51 UTC, ChenCMD requested changes

2021-02-06 11:51 UTC, ChenCMD commented on TheSkyBlock/data/core/functions/load_once.mcfunction
> +#> Dchedule
typo
```suggestion
#> Schedule
```

2021-02-06 11:51 UTC, ChenCMD commented on TheSkyBlock/data/core/functions/4_interval_tick.mcfunction
> +# @within function core:4_interval_tick
この記法で大丈夫
```suggestion
# @within function
#   core:load_once
#   core:4_interval_tick
```

2021-02-06 11:51 UTC, ChenCMD commented on TheSkyBlock/data/core/functions/4_interval_tick.mcfunction
> +schedule function core:4_interval_tick 4t
```suggestion
# ループの再設定
    schedule function core:4_interval_tick 4t
```

2021-02-06 11:51 UTC, ChenCMD commented on TheSkyBlock/data/core/functions/4_interval_tick.mcfunction
> +        execute as @a run function player_manager:mp_viewer/check_xpbar
インデント
```suggestion
# MP表示処理
    execute as @a run function player_manager:mp_viewer/check_xpbar
```

2021-02-06 11:51 UTC, ChenCMD commented on TheSkyBlock/data/player_manager/functions/mp_viewer/_.index.d.mcfunction
> +#> player_manager:mp_viewer/_.index.d
`_.index.d` -> `_index.d`かな

2021-02-06 11:51 UTC, ChenCMD commented on TheSkyBlock/data/player_manager/functions/mp_viewer/_.index.d.mcfunction
> +#   player_manager:mp_viewer/adjust_xpbar
これで大丈夫
```suggestion
# @within function player_manager:mp_viewer/**
```

2021-02-06 11:51 UTC, ChenCMD commented on TheSkyBlock/data/player_manager/functions/mp_viewer/adjust_xpbar.mcfunction
> +    xp set @s 40 levels
40lvを使う意図は？

2021-02-06 11:58 UTC, kaputina commented on TheSkyBlock/data/player_manager/functions/mp_viewer/adjust_xpbar.mcfunction
> +    xp set @s 40 levels
40lvのMaxPointが201で、2point刻みで1%毎の細かい指定ができたからです
28(max102)でもよかったんですが、切りのいい数字point(100)だと右にすこーし黒が残ってしまったのでよりいっぱいに表示されるように40lvを採用しました

2021-02-07 16:36 UTC, ChenCMD approved these changes
完璧

2021-02-07 16:37 UTC, merged

2021-02-07 16:37 UTC, ChenCMD commented
Fix #127