[神器0361] 極虹の水晶を作成
TheSkyBlock/TheSkyBlock pull request #136
Opened 2021-02-08 08:56 UTC by kaputina

攻撃していいMob判定はまだなので [🕒 wait for implementation] にお願いします

2021-03-06 12:58 UTC, ChenCMD requested changes
つくれるよ

2021-03-06 13:00 UTC, kaputina commented
了解です！
完全に忘れてました！

2021-03-07 12:27 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0361.rainbow_crystal/_.give.mcfunction
> +    data modify storage asset:sacred_treasure MPCost set value 99999
MP使用量がスプレッドシートと異なる
そもそもこのMPコスト、発動できないと思う

2021-03-07 12:27 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0361.rainbow_crystal/_.give.mcfunction
> +    data modify storage asset:sacred_treasure AttackInfo set value {AttackType:[Physical,Magic],ElementType:[Fire,Water,Thunder,None],BypassResist:0b}
ダメージ量を記載しないと???になってしまうと思うんだけど、意図した表現？

2021-03-07 12:27 UTC, kaputina commented on Asset/data/asset/functions/sacred_treasure/0361.rainbow_crystal/_.give.mcfunction
> +    data modify storage asset:sacred_treasure AttackInfo set value {AttackType:[Physical,Magic],ElementType:[Fire,Water,Thunder,None],BypassResist:0b}
です
撃つよアピールはしたくなかったので

2021-03-07 12:39 UTC, kaputina commented on Asset/data/asset/functions/sacred_treasure/0361.rainbow_crystal/_.give.mcfunction
> +    data modify storage asset:sacred_treasure MPCost set value 99999
Sheet変えてきました。
あれ、MP99999って発動できないんでしたっけ・・・？
MPRequireじゃないので行けると思ってました

2021-03-08 03:14 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0361.rainbow_crystal/_.give.mcfunction
> +    data modify storage asset:sacred_treasure MPCost set value 99999
MP消費量が99999で、MP必要量が未入力だと、MP必要量はMP消費量とイコールになるはずなので  
単純にMPが99999ないと発動できないと思います（実際にこの神器使ってみましたがそうでした。）  
MP必要量を指定すれば、すべてのMPを使用するけど要求するMPは0とかができるのではないでしょうか

2021-03-08 06:41 UTC, kaputina commented on Asset/data/asset/functions/sacred_treasure/0361.rainbow_crystal/_.give.mcfunction
> +    data modify storage asset:sacred_treasure MPCost set value 99999
そうだったんですか･･･！
MPRequire未記入の処理分かってませんでした･･･

2021-03-23 10:46 UTC, ChenCMD requested changes

2021-03-23 10:46 UTC, ChenCMD commented on Asset/data/asset/tags/functions/sacred_treasure/click.carrot_on_a_stick.json
> +        "asset:sacred_treasure/0365.bloodthirsty_sword/1.trigger",
```suggestion
```

2021-03-23 10:46 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0361.rainbow_crystal/3.main.mcfunction
> +        execute as @e[type=#lib:living,tag=Target,distance=..30] at @s run function lib:damage/
インデント、あとlib:damage/にat @sはいらない

2021-03-23 10:53 UTC, kaputina commented on Asset/data/asset/functions/sacred_treasure/0361.rainbow_crystal/3.main.mcfunction
> +        execute as @e[type=#lib:living,tag=Target,distance=..30] at @s run function lib:damage/
そういえば、damage_indicatorって自動でatしてくれるんですね･･･
忘れてました

2021-03-29 18:35 UTC, ChenCMD approved these changes

2021-03-29 18:36 UTC, merged