[神器0164] 加護のブーツを作成
TheSkyBlock/TheSkyBlock pull request #144
Opened 2021-02-09 16:08 UTC by tatuharu

2021-02-09 19:54 UTC, ChenCMD requested changes

2021-02-09 19:54 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0164.blessing_boots/2.check_condition.mcfunction
> +    scoreboard players reset @s Temporary
```suggestion
    execute if entity @s[y=0,dy=-255] run tag @s remove CanUsed
```

2021-02-09 20:03 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0164.blessing_boots/3.main.mcfunction
> +    execute in minecraft:overworld run tp @s 23 3 24
落下距離はそのままなので落下死します
低速落下をつけたほうがほうがいいよー

2021-02-10 05:40 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0164.blessing_boots/3.main.mcfunction
> +    execute in minecraft:overworld run tp @s 23 3 24
低速落下を付与しました。

2021-02-10 11:41 UTC, ChenCMD approved these changes

2021-02-10 11:41 UTC, merged