[神器0397]階層昇華の羽を作成
TheSkyBlock/TheSkyBlock pull request #145
Opened 2021-02-09 16:34 UTC by kemo14331

2021-02-09 19:46 UTC, ChenCMD requested changes
* 改行コードがCRLFになってる...?
* 右クリック神器なのにメインハンド限定でいいのかな

2021-02-09 19:46 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0397.floor_sublimation_wing/2.check_condition.mcfunction
> +    #declare tag 397.Marker
privateじゃない宣言は`~/_index.d.mcf`にまとめてね

2021-02-09 19:46 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0397.floor_sublimation_wing/2.check_condition.mcfunction
> +    kill @e[tag=397.Marker,limit=1]
軽量化のためdistance、もしくはdx/dy/dzを付けてほしい

2021-02-09 19:46 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0397.floor_sublimation_wing/3.main.mcfunction
> +        execute at @e[tag=397.Marker,limit=1] rotated as @s run tp @s ~ ~ ~
軽量化のため(ry

2021-02-09 19:46 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0397.floor_sublimation_wing/2.1.check_block.mcfunction
> +execute if score $397_Stat Temporary matches 1 run summon area_effect_cloud ~ ~1 ~ {Tags:["397.Marker"],Particle:"block air",Radius:0f,Age:-1,Duration:1}
```suggestion
# 加算
    scoreboard players add $397_Count Temporary 1

# 実行位置に条件を満たすブロックがあれば $397_Stat を1に
    execute unless block ~ ~ ~ air if block ~ ~1 ~ air if block ~ ~2 ~ air run scoreboard players set $397_Stat Temporary 1

# 32マスまで再起
    execute if score $397_Count Temporary matches ..32 if score $397_Stat Temporary matches 0 positioned ~ ~1 ~ run function asset:sacred_treasure/0397.floor_sublimation_wing/2.1.check_block

# 位置保存用AEC召喚
    execute if score $397_Stat Temporary matches 1 run summon area_effect_cloud ~ ~1 ~ {Tags:["397.Marker"],Particle:"block air",Radius:0f,Age:-1,Duration:1}
```

2021-02-11 13:12 UTC, ChenCMD requested changes

2021-02-11 13:12 UTC, ChenCMD commented on .vscode/settings.json
> +    "files.eol": "\n"
神器のPRでconfigを変更するのはあんまり芳しくないと思うのでmaster側でcommitしたのでこっちのは消しちゃってくだせ

2021-02-11 13:12 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0397.floor_sublimation_wing/2.1.check_block.mcfunction
> +#   function asset:sacred_treasure/0397.floor_sublimation_wing/2.1.check_block
これで大丈夫
```suggestion
# @within function
#   asset:sacred_treasure/0397.floor_sublimation_wing/2.check_condition
#   asset:sacred_treasure/0397.floor_sublimation_wing/2.1.check_block
```

2021-02-11 13:12 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0397.floor_sublimation_wing/2.check_condition.mcfunction
> +    kill @e[tag=397.Marker,distance=..32,limit=1]
type引数付けたほうがentityの検索は早いので付けたほうが良い
```suggestion
    kill @e[type=area_effect_cloud,tag=397.Marker,distance=..32,limit=1]
```

2021-02-11 13:12 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0397.floor_sublimation_wing/3.main.mcfunction
> +        execute at @e[tag=397.Marker,distance=..32,limit=1] rotated as @s run tp @s ~ ~ ~
以下同文
```suggestion
        execute at @e[type=area_effect_cloud,tag=397.Marker,distance=..32,limit=1] rotated as @s run tp @s ~ ~ ~
```

2021-02-11 17:06 UTC, kemo14331 commented
.vscode/settings.jsonの変更履歴を消す際にリベースしました
申し訳ないです

2021-02-18 16:27 UTC, ChenCMD requested changes
全体的に最初のreview時の指摘がそのままなのでそれ修正してくだせ

2021-02-18 17:10 UTC, kemo14331 commented
リベースしてぶっ飛んだところすっかり忘れてました…
すみません

2021-02-18 17:29 UTC, ChenCMD approved these changes

2021-02-18 17:31 UTC, merged