MotionLibを作成
TheSkyBlock/TheSkyBlock pull request #149
Opened 2021-02-10 07:01 UTC by kaputina

今後の他MotionLibFunction追加に備えてlib/motionを確保してあります

2021-02-10 19:58 UTC, ChenCMD requested changes
`$VectorX/Y/Z`,`lib: Pos`は毎tickリセットしてよさそう
それからMptoonLibMarkerは0-0-0-0-0に書き換えていい気がする(core側で召喚済

2021-02-11 00:09 UTC, kaputina commented
Entity毎にリセットするのって負荷的にはどうなんですかね・・・？
対象Entity数*4実行数が増える負荷とスコア-storageが存在することの負荷でどっちが高いのか
そこがいまいちわかってないのでこの実装にしてました
一応コーディング規約にのっとって修正してきます

2021-02-11 03:38 UTC, ChenCMD commented
> Entity毎にリセットするのって負荷的にはどうなんですかね・・・？
> 
> 対象Entity数*4実行数が増える負荷とスコア-storageが存在することの負荷でどっちが高いのか
> 
> そこがいまいちわかってないのでこの実装にしてました
> 
> 一応コーディング規約にのっとって修正してきます

そういうことならunless data storage lib: Posを条件にしてPosを求める処理をfunction分離して使い回す方がいいかも。

2021-02-11 03:45 UTC, kaputina commented
えっと･･･最初に共通のMotionを求めるってことですかね･･･？
だとしたら、向いてる向きが実行Entity毎で違う可能性があるのでこの実装じゃないとだめだと思います

2021-02-11 03:58 UTC, ChenCMD requested changes

2021-02-11 03:58 UTC, ChenCMD commented on TheSkyBlock/data/lib/functions/motion/_index.d.mcfunction
> +    #declare score_holder $VectorZ
このファイル消してもうprivate定義でいい気がする

2021-02-11 03:58 UTC, ChenCMD commented on TheSkyBlock/data/lib/functions/motion/core/apply.mcfunction
> +    tp 0-0-0-0-0 0.0 0.0 0.0
ここは保証しなくて良いと思う

2021-02-11 03:58 UTC, ChenCMD commented on TheSkyBlock/data/lib/functions/motion/core/apply.mcfunction
> +    execute store result storage lib: Pos[2] double 0.001 run scoreboard players get $VectorZ Temporary
$VectorX/Y/Z(x1000)×$VectorMagnitude(x100)だけどscale合ってる？

2021-02-11 03:58 UTC, ChenCMD commented on TheSkyBlock/data/lib/functions/motion/core/apply.mcfunction
> +    execute store result score $VectorZ Temporary run data get storage lib: Pos[2] 1000
0.01 × sinθの1000倍取得って相当な桁切り捨てられてないかな、ざっと計算しても1~2桁しか残らない気がする

2021-02-11 05:01 UTC, kaputina commented on TheSkyBlock/data/lib/functions/motion/core/apply.mcfunction
> +    execute store result storage lib: Pos[2] double 0.001 run scoreboard players get $VectorZ Temporary
最後の代入で0.001してるので大丈夫です
100でも良かったんですが、1000倍getは精緻さを高まるかな、と思っただけなので

2021-02-11 05:07 UTC, kaputina commented on TheSkyBlock/data/lib/functions/motion/core/apply.mcfunction
> +    execute store result score $VectorZ Temporary run data get storage lib: Pos[2] 1000
･･･確かにそうですね
デバッグ時点であまり分からなかったので少数以下の切り捨て具合殆ど考えてませんでした･･･
^ ^ ^1の1000Scale*引数を0.00001でstoreにするようにします

2021-02-11 05:13 UTC, kaputina commented on TheSkyBlock/data/lib/functions/motion/core/apply.mcfunction
> +    tp 0-0-0-0-0 0.0 0.0 0.0
8行目のtpのセレクター指定で軽量化のためにx=0を使ってた名残ですね･･･
UUID指定になったので削除します

2021-02-11 05:14 UTC, kaputina commented on TheSkyBlock/data/lib/functions/motion/_index.d.mcfunction
> +    #declare score_holder $VectorZ
了解です！
修正します

2021-02-11 13:24 UTC, ChenCMD requested changes

2021-02-11 13:24 UTC, ChenCMD commented on TheSkyBlock/data/lib/functions/motion/.mcfunction
> +# 実行座標の前方に$VectorMagnitude*100のMotionを付与します。
```suggestion
# 実行座標の前方に$VectorMagnitude*0.01の大きさのMotionを付与します。
```

2021-02-11 18:48 UTC, ChenCMD approved these changes

2021-02-11 18:50 UTC, merged