[神器0346]「我が下に集え」の作成
TheSkyBlock/TheSkyBlock pull request #157
Opened 2021-02-11 12:50 UTC by HamaSSH

Pull Request の方法が間違っていないことを願います
よろしくお願いしますm(_ _)m

2021-02-11 18:44 UTC, ChenCMD requested changes

2021-02-11 18:44 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0346.gather_around/3.main.mcfunction
> +        execute unless entity @e[type=#lib:living,distance=..30] run tellraw @s {"text":"全員集ご...！ 誰もいないみたいだ..."}
if/unlessは1体いればいいのでlimit=1をつけることで軽量化が望めるよ
```suggestion
    # 成功演出
        execute if entity @e[type=#lib:living,distance=..30,limit=1] run playsound minecraft:block.portal.travel master @a[distance=..30] ~ ~ ~ 0.3 2
        execute if entity @e[type=#lib:living,distance=..30,limit=1] run tellraw @a[distance=..30] [{"text":"["},{"selector":"@s"},{"text":"] "},{"text":"全員集合ーっ！","bold":true}]

    # 失敗演出
        execute unless entity @e[type=#lib:living,distance=..30,limit=1] run playsound minecraft:entity.villager.no master @s ~ ~ ~ 1 0.8
        execute unless entity @e[type=#lib:living,distance=..30,limit=1] run tellraw @s {"text":"全員集ご...！ 誰もいないみたいだ..."}
```

2021-02-12 05:50 UTC, HamaSSH commented on Asset/data/asset/functions/sacred_treasure/0346.gather_around/3.main.mcfunction
> +        execute unless entity @e[type=#lib:living,distance=..30] run tellraw @s {"text":"全員集ご...！ 誰もいないみたいだ..."}
なるほど... 勉強になります！

2021-02-12 14:00 UTC, ChenCMD approved these changes

2021-02-12 16:22 UTC, merged