[神器0064] 拳法の巻物を作成
TheSkyBlock/TheSkyBlock pull request #168
Opened 2021-02-15 16:31 UTC by tatuharu

2021-02-16 11:05 UTC, ChenCMD requested changes

2021-02-16 11:05 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0064.kenpo_scroll/2.check_condition.mcfunction
> +    execute as @s[nbt={SelectedItem:{}}] run tag @s remove CanUsed
asset:contextにmainhandのデータ入ってるのでそっち参照してね

2021-02-16 17:18 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0064.kenpo_scroll/2.check_condition.mcfunction
> +    execute as @s[nbt={SelectedItem:{}}] run tag @s remove CanUsed
あらほんと。たしかにそうね

2021-02-17 06:17 UTC, ChenCMD approved these changes

2021-02-17 06:17 UTC, merged