[神器0252]「奈落との契約」の作成
TheSkyBlock/TheSkyBlock pull request #174
Opened 2021-02-18 14:26 UTC by HamaSSH

2021-02-18 16:35 UTC, ChenCMD requested changes

2021-02-18 16:35 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0252.contract_with_the_void/3.main.mcfunction
> +    schedule function asset:sacred_treasure/0252.contract_with_the_void/3.1.void 120s
この方法だと干渉する(119秒のタイミングでもう一度子の神器を発動したりするとスケジュールが上書きされる)のでスコアボード増やして1tのschedule回して実装してね

2021-02-20 03:11 UTC, HamaSSH commented on Asset/data/asset/functions/sacred_treasure/0252.contract_with_the_void/3.main.mcfunction
> +    schedule function asset:sacred_treasure/0252.contract_with_the_void/3.1.void 120s
スコアボードの扱いがうまくいかずpredicateを使用しました。マルチでは動作確認ができていないのですが動くはずです。動作面負荷面で問題があれば指摘お願いしますm(_ _)m

2021-03-07 12:54 UTC, tatuharu requested changes

2021-03-07 12:54 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0252.void_transaction/3.1.initiation.mcfunction
> +    tag @s add Void
tickをまたぐ神器固有のタグの名前はできれば他と被らない固有の名前に変えてほしい！  
[ここ](https://github.com/TheSkyBlock/TheSkyBlock/wiki/convetion#12-%E5%91%BD%E5%90%8D%E8%A6%8F%E5%89%87)参照

2021-03-11 17:23 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0252.void_transaction/3.1.initiation.mcfunction
> +    tag @s add Void
説明がうまくできてなくてごめんね  
神器でobject, tag, score_holderを定義する際はほかの神器と干渉しないように、名前の先頭に`神器IDを64進数に変換した値.`をつけてね  
神器IDが123の場合：123の64進数 = 1Xなので、`1X.Owner`や`1X.Hit`などの命名にする  
64進数への変換は[ここ](https://www.muryou-tools.com/sinsuu-change.php)でできるよ

2021-03-12 14:30 UTC, HamaSSH commented on Asset/data/asset/functions/sacred_treasure/0252.void_transaction/3.1.initiation.mcfunction
> +    tag @s add Void
見落としてました、すみません...！

2021-03-19 10:24 UTC, ChenCMD requested changes
複数のファイルで利用するtagは~/_index.d.mcfに定義してね

2021-03-19 10:24 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0252.void_transaction/0.load.mcfunction
> +    scoreboard objectives add 0252.Timer dummy
こいつも64進数で良い気がする

2021-03-19 10:24 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0252.void_transaction/3.2.void.mcfunction
> +    execute if score @a[tag=3Y.Void,limit=1] 0252.Timer matches 1..2400 run schedule function asset:sacred_treasure/0252.void_transaction/3.2.void 1t replace
tagは0になった時点で消えるからif entityで良い気がするんだけど何か意図があるのかな

2021-03-19 10:24 UTC, ChenCMD commented on Asset/data/asset/tags/functions/sacred_treasure/load.json
> +        "asset:sacred_treasure/0456.potion_of_stalling_power/0.load",
```suggestion
```

2021-03-23 10:51 UTC, ChenCMD requested changes
if scoreを使うかif entity @s[scores={...を使うかの一貫性がないからどちらかに統一してね

2021-03-23 10:51 UTC, ChenCMD commented on Asset/data/asset/tags/functions/sacred_treasure/click.carrot_on_a_stick.json
> +        "asset:sacred_treasure/0078.self_destruct_order/1.trigger",
```suggestion
```

2021-03-24 05:03 UTC, ChenCMD approved these changes

2021-03-24 05:04 UTC, merged