[神器0088] 豊穣の鍬の作成
TheSkyBlock/TheSkyBlock pull request #182
Opened 2021-02-19 11:28 UTC by kaputina

2021-02-21 18:27 UTC, ChenCMD requested changes

2021-02-21 18:27 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0088.fertility_hoe/2.check_condition.mcfunction
> +        execute if entity @s[gamemode=!survival,gamemode=!creative] run tellraw @s [{"text": "ここでは使えなさそうだ..."}]
```suggestion
        execute if entity @s[gamemode=!survival,gamemode=!creative] run function lib:message/sacred_treasure/can_not_use_here
```

2021-02-21 18:27 UTC, ChenCMD commented on Asset/data/asset/tags/functions/sacred_treasure/click.carrot_on_a_stick.json
> +        "asset:sacred_treasure/0290.carefully_collector/1.trigger",
master側で直したからmergeしてね

2021-02-22 10:59 UTC, kaputina commented on Asset/data/asset/tags/functions/sacred_treasure/click.carrot_on_a_stick.json
> +        "asset:sacred_treasure/0290.carefully_collector/1.trigger",
了解です！

2021-02-23 11:42 UTC, ChenCMD approved these changes

2021-02-23 12:47 UTC, merged