[神器0333]鋼鬼針の作成
TheSkyBlock/TheSkyBlock pull request #183
Opened 2021-02-20 07:12 UTC by huyuyori

2021-02-21 18:09 UTC, ChenCMD requested changes

2021-02-21 18:09 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0333.koukisin/3.main.mcfunction
> +    execute at @e[type=#lib:living,type=!player,tag=AttackedEntity,distance=..10,limit=1] run particle minecraft:crit ~ ~1 ~ 0.2 0.8 0.2 0 80 normal @a[distance=..30]
[こっち](https://github.com/TheSkyBlock/TheSkyBlock/wiki/libraries#%E4%BD%BF%E3%81%84%E6%96%B9-3)使ってね

2021-02-21 18:09 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0333.koukisin/3.main.mcfunction
> +    execute as @e[type=#lib:living,type=!player,tag=AttackedEntity,distance=..10,limit=1] run function lib:damage/simple
lib:damage/simpleはparticle出ないからparticle出したいならlib:damage/を使ってね

2021-02-21 18:09 UTC, ChenCMD commented on Asset/data/asset/tags/functions/sacred_treasure/click.carrot_on_a_stick.json
> +        "asset:sacred_treasure/0290.carefully_collector/1.trigger",
master側でしたので消してヨシ
```suggestion
        "asset:sacred_treasure/0290.carefully_collector/1.trigger"
```

2021-02-24 06:19 UTC, ChenCMD requested changes

2021-02-24 06:19 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0333.koukisin/3.main.mcfunction
> +    execute as @e[type=#lib:living,type=!player,tag=AttackedEntity,distance=..10,limit=1] run function lib:damage/simple
particleを出さない貫通ダメージを与えたいならDamage以外のArgumetを消してlib:damage/simple、particleを出すならlib:damage/
(DisableParticle = falseはなんの意味もない(trueにしたときparticleが消えるので

2021-03-07 12:41 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0333.koukisin/3.main.mcfunction
> +    execute as @e[type=#lib:living,type=!player,tag=AttackedEntity,distance=..10,limit=1] run function lib:damage/simple
lib:damage/simpleは廃止されたので、lib/damageを継続して利用。  
今回は完全な貫通なので、信仰等による補正を回避するためmodifierを削除。  
敵に与えるダメージ情報を表示させる処理が実装されたので、それに対応させた。  
BypassResistを追加して貫通ダメージを与えるようにした。

2021-03-10 18:13 UTC, merged