Dev/tatuharu 297
TheSkyBlock/TheSkyBlock pull request #198
Opened 2021-02-25 13:30 UTC by tatuharu

2021-03-04 17:40 UTC, ChenCMD requested changes

2021-03-04 17:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.main.mcfunction
> +    summon armor_stand ~ ~ ~ {Tags:["4F.PosManager"],NoGravity:1b,Invulnerable:1b,Invisible:1b}
aecにしないと見えそう

2021-03-04 17:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.2.reset.mcfunction
> +    execute as @e[tag=4F.PosManager] if score @s 4F.UserID = @a[tag=4F.End,limit=1] 4F.UserID run tp @a[tag=4F.End,limit=1] @s
ディメンション移動とかされた時にやばそう

2021-03-04 17:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.1.trance.mcfunction
> +    execute as @a[tag=4F.Player,scores={4F.TickCount=0},limit=1] run function asset:sacred_treasure/0297.spirit_world_trance/3.2.reset
limit=1ついてる理由ってなんだろ

2021-03-07 12:07 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.1.trance.mcfunction
> +    execute as @a[tag=4F.Player,scores={4F.TickCount=0},limit=1] run function asset:sacred_treasure/0297.spirit_world_trance/3.2.reset
帰還処理を一人ずつ順番に処理したいからですね  
各々のUserIDにあう帰還場所に1人１人処理して返そうとしてます

2021-03-07 12:11 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.2.reset.mcfunction
> +    execute as @e[tag=4F.PosManager] if score @s 4F.UserID = @a[tag=4F.End,limit=1] 4F.UserID run tp @a[tag=4F.End,limit=1] @s
どの部分がディメンション移動されたときやばいのかがわかりませんでした...  
試しにOverWorldで霊界トランスを実行後、ネザーへとTPしましたが、10秒後には問題なく元のゲームモードでOverWorldに戻されました。

2021-03-07 12:15 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.main.mcfunction
> +    summon armor_stand ~ ~ ~ {Tags:["4F.PosManager"],NoGravity:1b,Invulnerable:1b,Invisible:1b}
確かに見えなかったのでAECにした

2021-03-10 18:27 UTC, ChenCMD requested changes
10秒だと対象のチャンクがunloadされる可能性ありそうだけどそこらへんどうだろ

2021-03-10 18:27 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.1.trance.mcfunction
> +    execute as @a[tag=4F.Player,scores={4F.TickCount=0},limit=1] run function asset:sacred_treasure/0297.spirit_world_trance/3.2.reset
この実装なら干渉しないからlimit=1はいらなさそう
```suggestion
    execute as @a[tag=4F.Player,scores={4F.TickCount=0}] run function asset:sacred_treasure/0297.spirit_world_trance/3.2.reset
```

2021-03-10 18:27 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.2.reset.mcfunction
> +    execute as @e[tag=4F.PosManager] if score @s 4F.UserID = @a[tag=4F.End,limit=1] 4F.UserID run tp @a[tag=4F.End,limit=1] @s
まじ？無知晒したわ

2021-03-10 18:27 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.2.reset.mcfunction
> +    execute as @e[tag=4F.PosManager] if score @s 4F.UserID = @a[tag=4F.End,limit=1] 4F.UserID run kill @s
```suggestion
    execute as @e[type=area_effect_cloud,tag=4F.PosManager] if score @s 4F.UserID = @a[tag=4F.End,limit=1] 4F.UserID run kill @s
```

2021-03-10 18:27 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.main.mcfunction
> +    scoreboard players operation @e[tag=4F.PosManager,sort=nearest,limit=1] 4F.UserID = $4F.UserManager 4F.UserID
```suggestion
    scoreboard players operation @e[type=area_effect_cloud,tag=4F.PosManager,sort=nearest,limit=1] 4F.UserID = $4F.UserManager 4F.UserID
```

2021-03-10 18:27 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.2.reset.mcfunction
> +    execute as @e[tag=4F.PosManager] if score @s 4F.UserID = @a[tag=4F.End,limit=1] 4F.UserID run tp @a[tag=4F.End,limit=1] @s
```suggestion
    execute as @e[type=area_effect_cloud,tag=4F.PosManager] if score @s 4F.UserID = @a[tag=4F.End,limit=1] 4F.UserID run tp @a[tag=4F.End,limit=1] @s
```

2021-03-10 18:28 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.2.reset.mcfunction
> +    execute as @e[tag=4F.PosManager] if score @s 4F.UserID = @a[tag=4F.End,limit=1] 4F.UserID run tp @a[tag=4F.End,limit=1] @s
まじ？無知晒したわ

2021-03-23 11:22 UTC, ChenCMD approved these changes

2021-03-23 11:22 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0297.spirit_world_trance/3.2.reset.mcfunction
> +#   function asset:sacred_treasure/0297.spirit_world_trance/3.1.trance
```suggestion
# @within function asset:sacred_treasure/0297.spirit_world_trance/3.1.trance
```

2021-03-23 11:24 UTC, merged