[神器0207]「夢幻泡影」の作成
TheSkyBlock/TheSkyBlock pull request #202
Opened 2021-02-27 12:05 UTC by HamaSSH

2021-02-28 08:01 UTC, ChenCMD requested changes

2021-02-28 08:01 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0207.life_is_transitory/3.main.mcfunction
> +        data remove storage lib: Argument
lib:score_to_health_wrapper/set使うと良さそう(wikiに乗せ忘れてるヤツ

2021-03-07 11:36 UTC, tatuharu reviewed
動作確認OK。スプレッドシートとの相違もなし。

2021-03-07 11:37 UTC, tatuharu approved these changes

2021-03-10 18:32 UTC, ChenCMD approved these changes

2021-03-22 08:40 UTC, merged