Dev/tatuharu 10
TheSkyBlock/TheSkyBlock pull request #206
Opened 2021-02-28 16:17 UTC by tatuharu

Friendのdeclareいらなくなったから外したよ

2021-03-01 11:59 UTC, ChenCMD requested changes

2021-03-01 11:59 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0010.attack_order/2.check_condition.mcfunction
> +    execute if entity @s[tag=!CanUsed] run function lib:message/sacred_treasure/can_not_use_here
この実装だとMPとかが足りなくてもここじゃ使えないって言われる

2021-03-02 10:19 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0010.attack_order/2.check_condition.mcfunction
> +    execute if entity @s[tag=!CanUsed] run function lib:message/sacred_treasure/can_not_use_here
そうだった

2021-03-04 17:32 UTC, ChenCMD approved these changes

2021-03-04 17:33 UTC, merged