Dev/uran2471 0218
TheSkyBlock/TheSkyBlock pull request #246
Opened 2021-03-10 14:07 UTC by uran247

屋内などで使うと天井に着弾するのは意図した仕様です

2021-03-19 10:14 UTC, ChenCMD requested changes

2021-03-19 10:14 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0218.iron_storm/3.main.mcfunction
> +    execute rotated ~ 0 positioned ^ ^ ^40 positioned ~-20 0 ~-20 as @e[type=iron_golem,tag=IronStormInit,tag=DA.Number9,dx=40,dy=320,dz=40] at @s run tp @s ~ 490 ~
entity:0-0-0-0-0を使うことでもうちょい良い実装になりそう、詳しいのは[これ](https://github.com/TheSkyBlock/TheSkyBlock/wiki/create-sacred-treasure#5-%E5%9F%BA%E6%9C%AC%E7%9A%84%E3%81%AA%E6%83%85%E5%A0%B1)

2021-03-19 10:14 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0218.iron_storm/3.1.entity_manager.mcfunction
> +    execute if entity @e[type=iron_golem,tag=DA.InAir] run schedule function asset:sacred_treasure/0218.iron_storm/3.1.entity_manager 1t replace
```suggestion
    execute if entity @e[type=iron_golem,tag=DA.InAir,limit=1] run schedule function asset:sacred_treasure/0218.iron_storm/3.1.entity_manager 1t replace
```

2021-03-19 10:14 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0218.iron_storm/3.3.blast.mcfunction
> +    scoreboard players operation $BlastDamage Temporary *= $DamageCoefficient Temporary
`100 - $Random % 70`じゃなくて`$Random % 70 + 30`でどうかな、こっちのほうが変数を一つ減らせる

2021-03-19 10:14 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0218.iron_storm/3.main.mcfunction
> +    summon iron_golem 0 0 0 {Tags:[IronStormInit,DA.Number9,DA.InAir],OnGround:0b}
[tag](https://github.com/TheSkyBlock/TheSkyBlock/wiki/tags)つけてね

2021-03-19 10:14 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0218.iron_storm/3.3.blast.mcfunction
> +    function lib:damage/modifier
modifierの対象がプレイヤーじゃない

2021-07-28 14:52 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0218.iron_storm/3.main.mcfunction
> +    execute rotated ~ 0 positioned ^ ^ ^40 positioned ~-20 0 ~-20 as @e[type=iron_golem,tag=IronStormInit,tag=DA.Number9,dx=40,dy=320,dz=40] at @s run tp @s ~ 490 ~
0-0-0-0-0を使うと1.17で問題が起こりそうだったため見送り

2021-07-28 14:53 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0218.iron_storm/3.3.blast.mcfunction
> +    function lib:damage/modifier
ダメージを与える主体がアイアンゴーレムである＋この実行タイミングだと神器使用者の特定が困難なためmodifierを除去

2021-08-19 06:34 UTC, ChenCMD approved these changes

2021-08-19 06:34 UTC, merged