[神器0467] コスモブルーフラッシュを実装
TheSkyBlock/TheSkyBlock pull request #248
Opened 2021-03-11 08:33 UTC by tatuharu

2021-03-12 11:19 UTC, ChenCMD requested changes

2021-03-12 11:19 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0467.cosmo_blue_flash/shot.mcfunction
> +    tag @s remove 7j.HitFlag
リセットは3.mainでよさそう(ここに書くと最大2*60回分メモリにわざわざ保持される

2021-03-12 11:19 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0467.cosmo_blue_flash/hit.mcfunction
> +    function lib:damage/modifier
modifierの対象がプレイヤーじゃない
```suggestion
    execute as @a[tag=this] run function lib:damage/modifier
```

2021-03-12 11:19 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0467.cosmo_blue_flash/3.main.mcfunction
> +    execute positioned ~ ~0.5 ~ run function asset:sacred_treasure/0467.cosmo_blue_flash/shot
視点位置...って意図ならこれでよさそう
```suggestion
    execute anchored eye positioned ^ ^ ^ run function asset:sacred_treasure/0467.cosmo_blue_flash/shot
```

2021-03-13 14:41 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0467.cosmo_blue_flash/3.main.mcfunction
> +    execute positioned ~ ~0.5 ~ run function asset:sacred_treasure/0467.cosmo_blue_flash/shot
execute anchored eyesだと、目線の位置なので、ターゲットの+がさしている位置よりもだいぶ上だった  
なので、結局~ ~0.5 ~ とやらないと、意図した位置に発射されなかった

2021-03-13 14:53 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0467.cosmo_blue_flash/shot.mcfunction
> +    tag @s remove 7j.HitFlag
リセットをmainで書くように修正しました

2021-03-19 09:50 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0467.cosmo_blue_flash/3.main.mcfunction
> +    execute positioned ~ ~0.5 ~ run function asset:sacred_treasure/0467.cosmo_blue_flash/shot
普通にparticleの座標にY+1してるからでは

2021-03-19 16:08 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0467.cosmo_blue_flash/3.main.mcfunction
> +    execute positioned ~ ~0.5 ~ run function asset:sacred_treasure/0467.cosmo_blue_flash/shot
マジだった

2021-03-20 14:43 UTC, ChenCMD approved these changes

2021-03-23 10:37 UTC, merged