[神器0462] 4・５・６ダイスを作成
TheSkyBlock/TheSkyBlock pull request #250
Opened 2021-03-13 18:00 UTC by tatuharu

2021-03-14 11:34 UTC, ChenCMD requested changes

2021-03-14 11:34 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0462.456_dice/3.main.mcfunction
> +    scoreboard players add @s Temporary 4
```suggestion
        scoreboard players add @s Temporary 4
```

2021-03-14 11:34 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0462.456_dice/3.main.mcfunction
> +    #declare score_holder $5
Constは正直宣言しなくてもいいのかなぁとは思ってる、するなら一行開けないとちょっとまずい
どちらかには変えてね
```suggestion

#> Private
# @private
    #declare score_holder $3
    #declare score_holder $5
```
```suggestion

2021-03-14 11:34 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0462.456_dice/3.main.mcfunction
> +            execute if score @s Temporary matches 2 run function asset:sacred_treasure/0462.456_dice/thunder
2コマンドなら普通にこのfunctionに普通に書いちゃっていい気がする(宣言を増やしたりfunctionを増やすのはちょっとアレな気がする

2021-03-14 11:34 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0462.456_dice/3.main.mcfunction
> +    tellraw @s [{"selector":"@s"},{"text":"はダイスを振った..."},{"score":{"name":"*","objective":"Temporary"}}]
これはなに

2021-03-14 18:45 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0462.456_dice/3.main.mcfunction
> +    scoreboard players add @s Temporary 4
確かに怪しいインデントだった

2021-03-14 18:47 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0462.456_dice/3.main.mcfunction
> +    tellraw @s [{"selector":"@s"},{"text":"はダイスを振った..."},{"score":{"name":"*","objective":"Temporary"}}]
ダイスを振って出た目をプレイヤーにチャットで通知してます

2021-03-19 09:46 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0462.456_dice/3.main.mcfunction
> +    tellraw @s [{"selector":"@s"},{"text":"はダイスを振った..."},{"score":{"name":"*","objective":"Temporary"}}]
正直`*`は明示的じゃないので普通に`@s`でいい気がする

2021-03-19 16:11 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0462.456_dice/3.main.mcfunction
> +    tellraw @s [{"selector":"@s"},{"text":"はダイスを振った..."},{"score":{"name":"*","objective":"Temporary"}}]
指摘通り@sに変更した

2021-03-20 14:33 UTC, ChenCMD approved these changes

2021-03-20 14:35 UTC, merged