神器のCoolDownが分表示もされるように
TheSkyBlock/TheSkyBlock pull request #261
Opened 2021-03-20 15:01 UTC by kaputina

2021-03-23 10:32 UTC, ChenCMD requested changes

2021-03-23 10:32 UTC, ChenCMD commented on TheSkyBlock/data/asset_manager/functions/sacred_treasure/core/create/set_cooltime.mcfunction
> +    tellraw @s [{"score":{"name": "$CooldownMinutes","objective": "Temporary"}}," ",{"score":{"name": "$Cooldown","objective": "Temporary"}}," ",{"score":{"name": "$CooldownDecimal","objective": "Tem
消し忘れ？

2021-03-23 10:32 UTC, ChenCMD commented on TheSkyBlock/data/asset_manager/loot_tables/sacred_treasure/core/generate_lore/cooldown.json
> +                                            "nbt": "{Tags:[HasMinutesCDFlag]}"
tagにするとdeserializeコストがかかるからスコアとか、その手の方法に変えてね

2021-03-23 10:32 UTC, ChenCMD commented on TheSkyBlock/data/asset_manager/loot_tables/sacred_treasure/core/generate_lore/special_cooldown.json
> +                                            "nbt": "{Tags:[HasMinutesCDFlag]}"
too

2021-03-23 10:58 UTC, kaputina commented on TheSkyBlock/data/asset_manager/functions/sacred_treasure/core/create/set_cooltime.mcfunction
> +    tellraw @s [{"score":{"name": "$CooldownMinutes","objective": "Temporary"}}," ",{"score":{"name": "$Cooldown","objective": "Temporary"}}," ",{"score":{"name": "$CooldownDecimal","objective": "Tem
です･･･
削除します

2021-03-23 10:59 UTC, kaputina commented on TheSkyBlock/data/asset_manager/loot_tables/sacred_treasure/core/generate_lore/cooldown.json
> +                                            "nbt": "{Tags:[HasMinutesCDFlag]}"
了解しました！
@sのTemporaryを使用します

2021-03-30 07:37 UTC, ChenCMD requested changes

2021-03-30 07:37 UTC, ChenCMD commented on TheSkyBlock/data/asset_manager/functions/sacred_treasure/core/create/set_cooltime.mcfunction
> +    execute if score $CooldownMinutes Temporary matches 1.. run scoreboard players set @s Temporary 1
インデント

2021-03-30 07:37 UTC, ChenCMD commented on TheSkyBlock/data/asset_manager/functions/sacred_treasure/core/create/set_special_cooltime.mcfunction
> +    execute if score $CooldownMinutes Temporary matches 1.. run scoreboard players set @s Temporary 1
インデント

2021-03-30 07:37 UTC, ChenCMD commented on TheSkyBlock/data/asset_manager/loot_tables/sacred_treasure/core/generate_lore/cooldown.json
> +                                    "Temporary": {
インデント

2021-04-04 09:28 UTC, ChenCMD approved these changes

2021-04-04 09:28 UTC, merged