player_manager:adjust_hunger/observeをschedule実行に
TheSkyBlock/TheSkyBlock pull request #265
Opened 2021-03-31 00:12 UTC by kaputina

2021-03-31 02:31 UTC, ChenCMD requested changes

2021-03-31 02:31 UTC, ChenCMD commented on TheSkyBlock/data/player_manager/functions/adjust_hunger/observe.mcfunction
> +# @within function player_manager:adjust_hunger/observe
```suggestion
# @within function
#   player_manager:adjust_hunger/respawn.delay
#   player_manager:adjust_hunger/observe
```

2021-03-31 02:31 UTC, ChenCMD commented on TheSkyBlock/data/player_manager/functions/adjust_hunger/observe.mcfunction
> +execute if entity @a[tag=AdjustHunger,limit=1] as @a[tag=AdjustHunger,tag=!Death] if score @s Hunger = @s HungerTarget run tag @s remove AdjustHunger
ここは一般に成功する確率の方が圧倒的に高いのでif entityは消すべき

2021-03-31 02:31 UTC, ChenCMD commented on TheSkyBlock/data/player_manager/functions/adjust_hunger/respawn.delay.mcfunction
> +schedule function player_manager:adjust_hunger/observe 1t replace
ここ、3行になるならhandler関数に直接書くべきじゃなさそう

2021-04-01 09:35 UTC, kaputina commented on TheSkyBlock/data/player_manager/functions/adjust_hunger/respawn.delay.mcfunction
> +schedule function player_manager:adjust_hunger/observe 1t replace
なるほど。player_manager:adjust_hunger/respawn.delayみたいなのつくりますかね...?

2021-04-01 10:07 UTC, ChenCMD commented on TheSkyBlock/data/player_manager/functions/adjust_hunger/respawn.delay.mcfunction
> +schedule function player_manager:adjust_hunger/observe 1t replace
startとかtriggerとか無名関数とかそんな感じの名前で良さそう

2021-04-02 12:04 UTC, ChenCMD approved these changes

2021-04-02 12:05 UTC, merged