各神器にUninterferableタグを対応
TheSkyBlock/TheSkyBlock pull request #266
Opened 2021-03-31 23:59 UTC by tatuharu

2021-04-02 09:03 UTC, ChenCMD requested changes

2021-04-02 09:03 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0355.barrel/3.main.mcfunction
> +        execute at @e[type=#lib:living,type=!player,tag=!Uninterferable,distance=..8] run summon armor_stand ~ ~1.8 ~ {Tags:["355.Barrel"],Marker:1b,Invisible:1b,ArmorItems:[{},{},{},{id:"minecraft:b
これ、何らかの判別タグとUninterferableを付けるべき

2021-04-02 23:35 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0355.barrel/3.main.mcfunction
> +        execute at @e[type=#lib:living,type=!player,tag=!Uninterferable,distance=..8] run summon armor_stand ~ ~1.8 ~ {Tags:["355.Barrel"],Marker:1b,Invisible:1b,ArmorItems:[{},{},{},{id:"minecraft:b
Enemyタグを追加しました。

2021-04-03 09:06 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0355.barrel/3.main.mcfunction
> +        execute at @e[type=#lib:living,type=!player,tag=!Uninterferable,distance=..8] run summon armor_stand ~ ~1.8 ~ {Tags:["355.Barrel"],Marker:1b,Invisible:1b,ArmorItems:[{},{},{},{id:"minecraft:b
上記のは樽の召喚先についての条件にEnemyタグを追加したということでした
樽自体にはFriend・Projectile・Uninterferableの３つのタグを付与しました

2021-04-04 09:24 UTC, ChenCMD approved these changes

2021-04-04 09:24 UTC, merged