神器ID210「テラブレード」を作成
TheSkyBlock/TheSkyBlock pull request #288
Opened 2021-05-17 19:47 UTC by Chuzume

2021-05-17 20:01 UTC, ChenCMD requested changes

2021-05-17 20:01 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0210.terra_blade/3.1.terra_shot_tick.mcfunction
> +    execute if entity @e[type=armor_stand,tag=ChuzTerraShot,limit=1] run schedule function asset:sacred_treasure/0210.terra_blade/3.1.terra_shot_tick 1t append
schedule appendは地獄
```suggestion
    execute if entity @e[type=armor_stand,tag=ChuzTerraShot,limit=1] run schedule function asset:sacred_treasure/0210.terra_blade/3.1.terra_shot_tick 1t
```

2021-05-18 17:32 UTC, ChenCMD requested changes
Spreadくんなくても行けそう

2021-05-18 17:32 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0210.terra_blade/3.main.mcfunction
> +    execute anchored eyes run summon armor_stand ^-0.35 ^ ^ {Marker:1b,Invisible:1b,Tags:["ChuzTerraShotInit","Projectile"]}
```suggestion
    execute anchored eyes run summon armor_stand ^-0.35 ^ ^ {Marker:1b,Invisible:1b,Tags:["ChuzTerraShotInit","Projectile","Uninterferable"]}
```

2021-05-18 17:32 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0210.terra_blade/3.1.terra_shot_tick.mcfunction
> +    execute as @e[type=armor_stand,tag=ChuzTerraShotInit] at @s run function asset:sacred_treasure/0210.terra_blade/3.2.terra_shot_init
initがループされてる

2021-05-27 10:19 UTC, ChenCMD requested changes

2021-05-27 10:19 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0210.terra_blade/3.2.terra_shot_init.mcfunction
> +    execute as @p[tag=210.This] at @s anchored eyes positioned ^ ^ ^ run function lib:forward_spreader/circle
神器実行処理とおなじtickだから普通にtag=thisじゃだめなのかな

2021-05-27 18:47 UTC, Chuzume commented on Asset/data/asset/functions/sacred_treasure/0210.terra_blade/3.2.terra_shot_init.mcfunction
> +    execute as @p[tag=210.This] at @s anchored eyes positioned ^ ^ ^ run function lib:forward_spreader/circle
万が一があると思いましたが、thisのほうが都合がいいのでしょうか

2021-05-27 18:48 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0210.terra_blade/3.2.terra_shot_init.mcfunction
> +    execute as @p[tag=210.This] at @s anchored eyes positioned ^ ^ ^ run function lib:forward_spreader/circle
そもそもthisはそういう用途だから普通にそれ使っていいと思うな

2021-05-28 16:49 UTC, ChenCMD approved these changes

2021-05-28 16:50 UTC, merged