[神器0087] 羊の加護を作成
TheSkyBlock/TheSkyBlock pull request #289
Opened 2021-05-18 13:09 UTC by tatuharu

2021-05-18 17:41 UTC, ChenCMD requested changes

2021-05-18 17:41 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0087.sheep_blessing/2.check_condition.mcfunction
> +    execute if score @s Temporary matches 0 run function lib:message/sacred_treasure/dont_have_require_items
リセット忘れてる

2021-05-18 17:41 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0087.sheep_blessing/3.main.mcfunction
> +function asset:sacred_treasure/0087.sheep_blessing/count_down
キニナルインデント

2021-05-28 03:56 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0087.sheep_blessing/2.check_condition.mcfunction
> +    execute if score @s Temporary matches 0 run function lib:message/sacred_treasure/dont_have_require_items
あらほんと

2021-05-28 03:56 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0087.sheep_blessing/3.main.mcfunction
> +function asset:sacred_treasure/0087.sheep_blessing/count_down
キニナッタカラナオシタ

2021-05-28 06:01 UTC, ChenCMD approved these changes

2021-05-30 14:51 UTC, merged