[神器0559-0561] ソリタリネスの作成
TheSkyBlock/TheSkyBlock pull request #296
Opened 2021-05-25 10:28 UTC by kaputina

2021-05-27 16:33 UTC, ChenCMD requested changes

2021-05-27 16:33 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0559.solitariness/3.main.mcfunction
> +            tag @s add Attacked
tag=thisでいいのでは

2021-05-30 07:39 UTC, kaputina commented on Asset/data/asset/functions/sacred_treasure/0559.solitariness/3.main.mcfunction
> +            tag @s add Attacked
あっ、、、存在を忘れてました、、、変更してきます！

2021-05-30 14:38 UTC, ChenCMD approved these changes

2021-05-30 14:38 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0559.solitariness/3.main.mcfunction
> +
```suggestion
```

2021-05-30 14:40 UTC, merged