[神器0605] 下克上を作成
TheSkyBlock/TheSkyBlock pull request #307
Opened 2021-06-05 12:21 UTC by tatuharu

2021-06-14 09:53 UTC, ChenCMD requested changes

2021-06-14 09:53 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0605.ambition/3.main.mcfunction
> +    execute store result score @s Temporary run data get storage oh_my_dat: _[-4][-4][-4][-4][-4][-4][-4][-4].LostItems
後々OhMyDatはやっぱり非公開にしてAPIを作るのでそれまで待って欲しいかも

2021-06-29 17:30 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0605.ambition/3.main.mcfunction
> +    execute store result score @s Temporary run data get storage oh_my_dat: _[-4][-4][-4][-4][-4][-4][-4][-4].LostItems
[作ったのでこれつかってくだせ](https://github.com/TheSkyBlock/TheSkyBlock/wiki/api#%E6%B2%A1%E5%8F%8E%E3%82%A2%E3%82%A4%E3%83%86%E3%83%A0%E6%95%B0%E5%8F%96%E5%BE%97)

2021-07-26 02:47 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0605.ambition/3.main.mcfunction
> +    execute store result score @s Temporary run data get storage oh_my_dat: _[-4][-4][-4][-4][-4][-4][-4][-4].LostItems
作られたのでそれ使うね

2021-07-28 10:05 UTC, ChenCMD approved these changes

2021-07-28 10:05 UTC, merged