[神器607~608]U&W-06作成
TheSkyBlock/TheSkyBlock pull request #310
Opened 2021-06-06 08:48 UTC by quikku

2021-06-14 09:51 UTC, ChenCMD requested changes

2021-06-14 09:51 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0607.u_and_w_06/3.main.mcfunction
> +    execute if score $UseCount Temporary matches 1 run function asset:sacred_treasure/0608.u_and_w_06_empty/_.give
これ、処理的に残り使用回数が2 -> 1になった時にも発動しそう(回避策がない気もするのでこっちで直した方がよければ言ってね

2021-06-14 09:51 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0607.u_and_w_06/3.main.mcfunction
> +    execute as @s facing entity 0-0-0-0-0 feet anchored eyes positioned ^ ^ ^ run function asset:sacred_treasure/0607.u_and_w_06/3.1.bullet
```suggestion
    execute facing entity 0-0-0-0-0 feet anchored eyes positioned ^ ^ ^ run function asset:sacred_treasure/0607.u_and_w_06/3.1.bullet
```

2021-06-14 09:51 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0607.u_and_w_06/3.1.bullet.mcfunction
> +    execute if entity @e[type=#lib:living,type=!player,tag=!Uninterferable,dx=0] run tag @s add Landing
この当たり判定、xyz+方向にしか判定ない気がするけど仕様？

2021-06-14 12:07 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0607.u_and_w_06/3.main.mcfunction
> +    execute if score $UseCount Temporary matches 1 run function asset:sacred_treasure/0608.u_and_w_06_empty/_.give
あっれ、普通に動いてたけどなんかまずいんか
確認はしてみるね

2021-06-15 10:40 UTC, ChenCMD approved these changes

2021-06-15 10:47 UTC, merged