[モブ0021] デーモンアイを作成
TheSkyBlock/TheSkyBlock pull request #330
Opened 2021-07-10 17:00 UTC by Chuzume

2021-07-27 16:52 UTC, ChenCMD requested changes
ゆるして

2021-07-27 16:52 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0021.demon_eye/tick/2.tick.mcfunction
> +    execute if data storage api: {HurtTime:0s} rotated as @e[type=area_effect_cloud,tag=21.Rotater,sort=nearest,limit=1] run function lib:motion/
api:data_get/*はMOBに対して使うとむしろ重くなるので普通に書いて(wikiに書き忘れてました 申し訳ございません！！！！！！

2021-07-27 16:52 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0021.demon_eye/tick/2.tick.mcfunction
> +    execute if data storage api: {OnGround:1b} positioned ~ ~1.5 ~ as @e[type=area_effect_cloud,tag=21.Rotater,sort=nearest,limit=1] at @s run tp @s ~ ~ ~ ~ ~-35
```suggestion
    function api:data_get/on_ground
    execute if data entity @s {OnGround:1b} positioned ~ ~1.5 ~ as @e[type=area_effect_cloud,tag=21.Rotater,sort=nearest,limit=1] at @s run tp @s ~ ~ ~ ~ ~-35
```

2021-07-27 16:52 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0021.demon_eye/tick/attack.mcfunction
> +    execute if data storage api: {HurtTime:0s} run function lib:damage/
修正するときに`~/tick/2.tick.mcf`の15行のところと合わせて一度storageにHurtTimeを保存してそこからdata storageでチェックするとよさそう

2021-10-29 20:44 UTC, Chuzume commented on Asset/data/asset/functions/mob/0021.demon_eye/tick/attack.mcfunction
> +    execute if data storage api: {HurtTime:0s} run function lib:damage/
モブにapi:data_get/*を使ってはいけないのでは…？

2021-10-29 21:13 UTC, Chuzume commented
橙主任へ:
どうやらPassengersのほうには"AssetMob"のタグが付与されないらしく、死亡時のfunctionにわざわざAECをキルするコマンドを書いていた理由はおそらくそれです　AECのほうに勝手にAssetMobを書き足したのですが大丈夫だと信じています

2021-10-31 06:24 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0021.demon_eye/tick/attack.mcfunction
> +    execute if data storage api: {HurtTime:0s} run function lib:damage/
あ、普通にstorageにmodifyで突っ込む感じ(説明が悪かった
```mcfunction
data modify storage asset:temp HurtTime set from entity @s HurtTime
```

2021-10-31 06:50 UTC, ChenCMD requested changes

2021-10-31 06:50 UTC, ChenCMD commented on Asset/data/asset/tags/functions/mob/load.json
> +        "asset:mob/0027.skull_sniper/0.load",
増えちゃってるから消そう
```suggestion
```

2021-10-31 06:50 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0021.demon_eye/tick/2.tick.mcfunction
> +    execute if data entity @s {OnGround:1b} positioned ~ ~1.5 ~ as execute if data storage api: {OnGround:1b} positioned ~ ~1.5 ~ as @e[type=area_effect_cloud,tag=21.Rotater,sort=nearest,limit=1] at
`as execute`で草(これエラーにならないんだ(怖い
```suggestion
    execute if data entity @s {OnGround:1b} positioned ~ ~1.5 ~ as @e[type=area_effect_cloud,tag=21.Rotater,sort=nearest,limit=1] at @s run tp @s ~ ~ ~ ~ ~-35
```

2021-10-31 06:50 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0021.demon_eye/tick/rotater_tick.mcfunction
> +    execute store result entity @s Rotation[1] float 0.001 run scoreboard players get $21.RotY 21.Rot
こうするとより軽量(後、ここでasset:temp Rotationをリセットしていないのは`~/tick/2.tick.mcf`で軽量にRotationを取得するため
```suggestion
# Rotation取得
    data modify storage asset:temp Rotation set from entity @s Rotation
# ホーミング
    execute store result score $21.RotX 21.Rot run data get storage asset:temp Rotation[0] 1000
    execute store result score $21.RotY 21.Rot run data get storage asset:temp Rotation[1] 1000

# 回転角度取得
    scoreboard players set $21.AngleX 21.Rot 0
    scoreboard players set $21.AngleY 21.Rot 0

# X軸の振り向き速度
    scoreboard players add $21.AngleX 21.Rot 1500

# Y軸の振り向き速度
    scoreboard players add $21.AngleY 21.Rot 3000

# 回転角度加算
    execute rotated as @s positioned as @a[distance=..100] positioned ^-100 ^ ^ positioned as @s[distance=..100] run scoreboard players operation $21.RotX 21.Rot -= $21.AngleY 21.Rot
    execute rotated as @s positioned as @a[distance=..100] positioned ^100 ^ ^ positioned as @s[distance=..100] run scoreboard players operation $21.RotX 21.Rot += $21.AngleY 21.Rot
    execute rotated as @s positioned as @a[distance=..100] positioned ^ ^-100 ^ positioned as @s[distance=..100] run scoreboard players operation $21.RotY 21.Rot -= $21.AngleX 21.Rot
    execute rotated as @s positioned as @a[distance=..100] positioned ^ ^100 ^ positioned as @s[distance=..100] run scoreboard players operation $21.RotY 21.Rot += $21.AngleX 21.Rot

# セット
    execute store result storage asset:temp Rotation[0] float 0.001 run scoreboard players get $21.RotX 21.Rot
    execute store result storage asset:temp Rotation[1] float 0.001 run scoreboard players get $21.RotY 21.Rot
    data modify entity @s Rotation set from storage asset:temp Rotation
```

2021-10-31 06:50 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0021.demon_eye/tick/2.tick.mcfunction
> +    data modify entity @s Rotation set from entity @e[type=area_effect_cloud,tag=21.Rotater,sort=nearest,limit=1] Rotation
`~/tick/rotater_tick.mcf`と合わせてこれで軽量に方向を代入できる(はず....)
```suggestion
    data modify entity @s Rotation set from storage asset:temp Rotation
    data remove storage asset:temp Rotation
```

2021-10-31 07:04 UTC, ChenCMD approved these changes

2021-10-31 07:04 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0021.demon_eye/tick/2.tick.mcfunction
> +    execute if entity @s[nbt={HurtTime:0s}] at @s anchored eyes rotated as @e[type=area_effect_cloud,tag=21.Rotater,sort=nearest,limit=1] run function lib:motion/
27行目と一貫性がなくて気になったので勝手に修正するぜ
```suggestion
    execute if data entity @s {HurtTime:0s} at @s anchored eyes rotated as @e[type=area_effect_cloud,tag=21.Rotater,sort=nearest,limit=1] run function lib:motion/
```

2021-10-31 07:05 UTC, merged