[mob56] 雷弄者の作成
TheSkyBlock/TheSkyBlock pull request #333
Opened 2021-07-22 16:25 UTC by Lapis-LJA

2.hurtにあるブロックタグはこれから出します

2021-07-23 01:18 UTC, quikku commented on Asset/data/asset/functions/mob/0056.thunder_trifler/hurt/2.hurt.mcfunction
> +    execute facing entity @p[tag=Attacker] eyes rotated ~ 0 run function lib:forward_spreader/circle
```suggestion
    execute at @p[tag=Attacker] positioned ~ ~25 ~ rotated ~ 90 run function lib:forward_spreader/circle
```

2021-07-23 01:18 UTC, quikku commented on Asset/data/asset/functions/mob/0056.thunder_trifler/hurt/2.hurt.mcfunction
> +    execute at 0-0-0-0-0 if block ~ ~ ~ #asset:mob/0056.thunder_trifler/no_collision unless block ~ ~-1 ~ #asset:mob/0056.thunder_trifler/no_collision run tp @s 0-0-0-0-0
```suggestion
    execute at @p[tag=Attacker] positioned ~ ~25 ~ facing entity 0-0-0-0-0 feet positioned ^ ^ ^25 if block ~ ~ ~ #asset:mob/0056.thunder_trifler/no_collision unless block ~ ~-1 ~ #asset:mob/0056.thunder_trifler/no_collision run tp @s ~ ~ ~
```
もしかしてだけどこういうことやりたかったんじゃないかな...

2021-07-23 01:24 UTC, quikku commented on Asset/data/asset/functions/mob/0056.thunder_trifler/hurt/2.hurt.mcfunction
> +    execute at 0-0-0-0-0 if block ~ ~ ~ #asset:mob/0056.thunder_trifler/no_collision unless block ~ ~-1 ~ #asset:mob/0056.thunder_trifler/no_collision run tp @s 0-0-0-0-0
```suggestion
    execute at @p[tag=Attacker] positioned ~ ~25 ~ rotated ~ 90 run function lib:forward_spreader/circle
    execute at @p[tag=Attacker] positioned ~ ~25 ~ facing entity 0-0-0-0-0 feet positioned ^ ^ ^25 if block ~ ~ ~ #asset:mob/0056.thunder_trifler/no_collision unless block ~ ~-1 ~ #asset:mob/0056.thunder_trifler/no_collision run tp @s ~ ~ ~
```
おそらくこういうことをしたかったのでは
さっきまでだとプレイヤーめがけて前方拡散する都合上ほとんどの確率でテレポできないし確実に10m離れる
これはまあ大体エンダーマン的な動きになる

2021-07-23 01:45 UTC, quikku commented on Asset/data/asset/predicates/mob/0056.thunder_trifler/bow.json
> +                ]
```suggestion
                "item":
                    "minecraft:bow"
```
なんか動いてなかったよ

2021-07-23 01:45 UTC, quikku commented on Asset/data/asset/predicates/mob/0056.thunder_trifler/golden_sword.json
> +                ]
```suggestion
                "item":
                    "minecraft:golden_sword"
```
なんか動いてなかったよ
itemsじゃなくてitemに変えて[]を消したら動いた

2021-07-23 07:38 UTC, ChenCMD commented on Asset/data/asset/predicates/mob/0056.thunder_trifler/bow.json
> +                ]
1.17の記法で書いちゃってたわ

2021-07-28 10:52 UTC, ChenCMD requested changes

2021-07-28 10:52 UTC, ChenCMD commented on Asset/data/asset/predicates/mob/0056.thunder_trifler/golden_sword.json
> +                    "minecraft:golden_sword"            }
```suggestion
                "item": "minecraft:golden_sword"
            }
```

2021-07-28 11:00 UTC, ChenCMD approved these changes

2021-07-28 11:21 UTC, merged