虚闘者(弓)の作成
TheSkyBlock/TheSkyBlock pull request #337
Opened 2021-07-24 14:32 UTC by Lapis-LJA

2021-07-31 12:24 UTC, quikku commented on Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/8.glowing_state.mcfunction
> +#> asset:mob/0059.jack_o_lantern/tick/7.glowing_state
7じゃなくて8

2021-08-19 04:00 UTC, ChenCMD requested changes

2021-09-15 06:46 UTC, ChenCMD requested changes

2021-09-15 06:46 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0059.jack_o_lantern/tick/4.glowing_state.mcfunction
> +#> asset:mob/0059.jack_o_lantern/tick/4.glowing_state
glowing_stateって単純に言葉としておかしい気がするけど私の気のせいだろうか

2021-11-15 12:52 UTC, ChenCMD approved these changes

2021-11-19 12:45 UTC, quikku commented on Asset/data/asset/functions/mob/0059.jack_o_lantern/summon/2.summon.mcfunction
> +    summon zombie ~ ~ ~ {Silent:1b,Tags:["MobInit","AlwaysInvisible","AntiDrown","AntiVoid"],DeathLootTable:"asset:mob/death/0059.jack_o_lantern"}
```suggestion
    summon zombie ~ ~ ~ {Silent:1b,Tags:["MobInit","AlwaysInvisible","AntiVoid"],DeathLootTable:"asset:mob/death/0059.jack_o_lantern"}
```

2021-11-22 09:13 UTC, ChenCMD approved these changes

2021-12-02 05:17 UTC, merged