Dev/lapis 624 627
TheSkyBlock/TheSkyBlock pull request #361
Opened 2021-07-28 15:44 UTC by Lapis-LJA

2021-07-29 09:26 UTC, quikku commented
アイスブーツが入ってる
消してね！！

ブランチを分けるときにマスター戻らないとこうなる

2021-07-31 10:22 UTC, quikku commented
dis_equip.json
equip.json
にまだアイスブーツいる！！！！！！！！！消して！！！！！！！！

2021-08-19 06:10 UTC, ChenCMD requested changes
#357 のChanges Requestを参考に修正してね

2021-09-16 04:29 UTC, ChenCMD requested changes

2021-09-16 04:29 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0625.flame_armor/4.fullset.mcfunction
> +# @within function asset:sacred_treasure/0626.flame_leggings/3.main
このwithinだけは許せない(あまりにもきれいではない

2021-11-15 12:54 UTC, ChenCMD approved these changes

2021-11-15 12:55 UTC, merged