[神器642]雷鳴を作成
TheSkyBlock/TheSkyBlock pull request #364
Opened 2021-07-31 11:54 UTC by quikku

2021-08-06 09:35 UTC, ChenCMD requested changes

2021-08-06 09:35 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0643.raimei_chestplate/3.main.mcfunction
> +    execute if data storage asset:context {Inventory:[{Slot:103b,tag:{TSB:{ID:642}}},{Slot:102b,tag:{TSB:{ID:643}}},{Slot:101b,tag:{TSB:{ID:644}}},{Slot:100b,tag:{TSB:{ID:645}}}]} run function asset:
これ、普通にid参照すればいい気がする

2021-08-06 09:35 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0642.raimei_helmet/3.main.mcfunction
> +    execute if data storage asset:context {Inventory:[{Slot:103b,tag:{TSB:{ID:642}}},{Slot:102b,tag:{TSB:{ID:643}}},{Slot:101b,tag:{TSB:{ID:644}}},{Slot:100b,tag:{TSB:{ID:645}}}]} run function asset:
直接id(ry

2021-08-06 09:35 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0644.raimei_leggings/3.main.mcfunction
> +    execute if data storage asset:context {Inventory:[{Slot:103b,tag:{TSB:{ID:642}}},{Slot:102b,tag:{TSB:{ID:643}}},{Slot:101b,tag:{TSB:{ID:644}}},{Slot:100b,tag:{TSB:{ID:645}}}]} run function asset:
直(ry

2021-08-06 09:35 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0645.raimei_boots/3.main.mcfunction
> +    execute if data storage asset:context {Inventory:[{Slot:103b,tag:{TSB:{ID:642}}},{Slot:102b,tag:{TSB:{ID:643}}},{Slot:101b,tag:{TSB:{ID:644}}},{Slot:100b,tag:{TSB:{ID:645}}}]} run function asset:
c(ry

2021-08-13 08:11 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0643.raimei_chestplate/3.main.mcfunction
> +    execute if data storage asset:context {Inventory:[{Slot:103b,tag:{TSB:{ID:642}}},{Slot:102b,tag:{TSB:{ID:643}}},{Slot:101b,tag:{TSB:{ID:644}}},{Slot:100b,tag:{TSB:{ID:645}}}]} run function asset:
execute if data storage asset:context id{head:642,chest:643,legs:644,feet:645} ...
こういうこと？動かないんだなこれが

2021-09-16 04:32 UTC, ChenCMD approved these changes

2021-09-16 04:48 UTC, merged