AntiFrozenの汎用tag作成
TheSkyBlock/TheSkyBlock pull request #372
Opened 2021-08-05 11:59 UTC by Lapis-LJA

正直弾かれる未来が見える

2021-08-06 08:35 UTC, ChenCMD requested changes

2021-08-06 08:35 UTC, ChenCMD commented on TheSkyBlock/data/asset_manager/functions/mob/common_tag/check_frozen.mcfunction
> +#
説明

2021-08-06 08:35 UTC, ChenCMD commented on TheSkyBlock/data/asset_manager/functions/mob/common_tag/check_frozen.mcfunction
> +    execute if score $Frozen Temporary matches 1.. run data modify entity @s StrayConversionTime set value 100000
これだと結局毎tick設定されるので`1 <= $Frozen <= 300`にするべき

2021-08-06 10:23 UTC, Lapis-LJA commented on TheSkyBlock/data/asset_manager/functions/mob/common_tag/check_frozen.mcfunction
> +    execute if score $Frozen Temporary matches 1.. run data modify entity @s StrayConversionTime set value 100000
この場合は新規にスコアが300のobjectives追加したほうがいいってことでいいんですかね

2021-08-06 10:59 UTC, ChenCMD requested changes

2021-08-06 10:59 UTC, ChenCMD commented on TheSkyBlock/data/asset_manager/functions/mob/common_tag/check_frozen.mcfunction
> +    execute if score $Frozen Temporary matches ..300 run data modify entity @s StrayConversionTime set value 100000
通常時-1に設定されてるから1..300にするべき

2021-08-07 06:37 UTC, ChenCMD commented
IMP-Docに説明足してね

2021-08-08 18:16 UTC, ChenCMD approved these changes

2021-08-08 18:17 UTC, merged