Dev/huyuyori
TheSkyBlock/TheSkyBlock pull request #43
Opened 2020-12-28 12:40 UTC by huyuyori

[神器0078] 自爆命令を作成 ダメージ数値は後々Mob側の基準に合わせて変更

2020-12-28 12:47 UTC, ChenCMD requested changes

2020-12-28 12:47 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/3.1.explosion_manager.mcfunction
> +    tp @e[tag=GolemBomb] ~ -100 ~
これ、-100だとプレイヤーの座標次第じゃ生き残る

2020-12-28 12:47 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/3.1.explosion_manager.mcfunction
> +      # 与えるダメージ = 7.5
怪しいインデント

2020-12-28 12:47 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/3.main.mcfunction
> +    schedule function asset:sacred_treasure/0078.self_destruct_order/3.1.explosion_manager 60t replace
この記述だとこの神器をタイミングずらして数回使った時に予期しない挙動起きるので、工夫が必要

2020-12-28 12:48 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/3.1.explosion_manager.mcfunction
> +    tp @e[tag=GolemBomb] ~ -100 ~
いや、これは0 0 0だから大丈夫なのか

2021-03-02 12:04 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/3.1.explosion_manager.mcfunction
> +    tp @e[tag=GolemBomb] ~ -100 ~
怪しかったので一応killするようにした

2021-03-02 12:04 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/3.1.explosion_manager.mcfunction
> +      # 与えるダメージ = 7.5
怪しいインデント修正した

2021-03-02 12:05 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/3.main.mcfunction
> +    schedule function asset:sacred_treasure/0078.self_destruct_order/3.1.explosion_manager 60t replace
スコアボード加算で1tスケジュールまわして工夫した

2021-03-04 17:31 UTC, ChenCMD requested changes
3秒後に5マス以内にゴーレムが存在しない可能性があるのでタグを削除するなりスコアの加算対象をゴーレムにするなり工夫が必要そう

2021-03-04 17:31 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/2.check_condition.mcfunction
> +    execute unless entity @e[type=iron_golem,type=snow_golem,distance=..15] run tag @s remove CanUsed
これ動作しなさそう

2021-03-04 17:31 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/explosion.mcfunction
> +    data remove storage lib: Argument
これダメージ与える必要ある？(どうせtp+killしてるので

2021-03-05 11:26 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/explosion.mcfunction
> +    data remove storage lib: Argument
ダメージを与えてるのはゴーレムの周りにいる周囲の生物に対して与えてます。
一方TPとKILLをしているのは、ゴーレム自身です

2021-03-06 01:35 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/2.check_condition.mcfunction
> +    execute unless entity @e[type=iron_golem,type=snow_golem,distance=..15] run tag @s remove CanUsed
おっしゃる通り動作しなかったので修正

2021-03-06 01:36 UTC, tatuharu commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/explosion.mcfunction
> +    data remove storage lib: Argument
と思ってたんだけど、ゴーレムの周りにダメージを与える処理でゴーレムにもダメージ与えてしまっていたので、そこは修正

2021-03-06 12:53 UTC, ChenCMD requested changes
まだセレクター周りが怪しそう、tag付きの対象全員killしてる

2021-03-06 12:53 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/explosion.mcfunction
> +        data modify storage lib: Argument.BypassArmor set value true
```suggestion
```

2021-03-06 12:53 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/explosion.mcfunction
> +        data modify storage lib: Argument.DisableParticle set value false
falseなら書かなくても大丈夫
```suggestion
```

2021-03-06 12:53 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0078.self_destruct_order/explosion.mcfunction
> +        data modify storage lib: Argument.BypassArmor set value true
👆
```suggestion
```

2021-03-07 11:48 UTC, tatuharu commented
> まだセレクター周りが怪しそう、tag付きの対象全員killしてる

tagつきの対象を全員killしないと、爆破対象となったゴーレムが全員爆破できないのでこうしてます  
神器にグローバルクールダウン3秒がついてるので、同時にほかのプレイヤーが重ねて使用することはないので大丈夫かと思われます。

2021-03-10 18:06 UTC, ChenCMD approved these changes

2021-03-10 18:09 UTC, merged