[MOB131]ハルクレアを作成
TheSkyBlock/TheSkyBlock pull request #456
Opened 2021-10-30 04:15 UTC by quikku

2021-12-09 12:45 UTC, ChenCMD requested changes

2021-12-09 12:45 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0131.haruclaire/tick/skill_ice_area/partile.mcfunction
> +#> asset:mob/0131.haruclaire/tick/skill_ice_area/partile
```diff
- partile
+ particle
```

2021-12-09 12:45 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0131.haruclaire/tick/skill_ice_canon/1.skill_ice_cannon.mcfunction
> +    execute if score @s 3N.Tick matches 1 run data modify entity @e[type=armor_stand,tag=3N.ArmorStand,distance=..0.01,sort=nearest,limit=1] Pose.RightArm set value [270f,0f,0f]
↑

2021-12-09 12:45 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0131.haruclaire/tick/skill_ice_pillar/1.skill_ice_pillar.mcfunction
> +    execute if score @s 3N.Tick matches 1 run data modify entity @e[type=armor_stand,tag=3N.ArmorStand,distance=..0.01,sort=nearest,limit=1] Pose.RightArm set value [0f,0f,90f]
↑

2021-12-09 12:45 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0131.haruclaire/tick/skill_ice_pillar/2.skill_ice_pillar_aec_summon.mcfunction
> +    execute as @e[type=marker,tag=SpreadMarker] at @p positioned ~ ~20 ~ rotated ~ 90 run function lib:forward_spreader/circle
distanceほしいかな

2021-12-09 12:45 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0131.haruclaire/tick/skill_ice_pillar/2.skill_ice_pillar_aec_summon.mcfunction
> +    execute at @p positioned ~ ~20 ~ facing entity @e[type=marker,tag=SpreadMarker] feet run summon area_effect_cloud ^ ^ ^20 {CustomNameVisible:0b,Particle:"block air",Duration:90,Tags:["Object","3N
↑

2021-12-09 12:45 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0131.haruclaire/tick/skill_ice_pillar/1.skill_ice_pillar.mcfunction
> +    execute if score @s 3N.Tick matches 45..50 at @e[type=area_effect_cloud,tag=3N.SkillPillarMaker,sort=random,limit=5] run function asset:mob/0131.haruclaire/tick/skill_ice_pillar/3.skill_ice_pilla
distance

2021-12-09 12:45 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0131.haruclaire/0.load.mcfunction
> +    scoreboard objectives add 3N.4tInterval dummy
unused

2021-12-11 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0131.haruclaire/tick/skill_ice_area/1.skill_ice_area.mcfunction
> +    execute if score @s 3N.Tick matches 1 run data modify entity @e[type=armor_stand,tag=3N.ArmorStand,distance=..0.01,sort=nearest,limit=1] Pose.RightArm set value [205f,44f,0f]
これねー...ただポーズ変えてるだけじゃなくて一応アニメーションさせる予定があるかもしれない関係上まとめちゃうと見にくいのよね
アニメーションのやりやすさ重視しちゃった感じ
ただ結局アニメーションさせてないからどうなんだって感じするけど

2021-12-11 13:01 UTC, quikku commented on Asset/data/asset/functions/mob/0131.haruclaire/hurt/2.hurt.mcfunction
> +#> asset:mob/0131.haruclaire/hurt/2.hurt
どっちかっていうと処理がなぜか入れてなかった

2021-12-13 06:00 UTC, ChenCMD approved these changes

2021-12-13 06:00 UTC, merged

2021-12-13 06:20 UTC, ChenCMD approved these changes