[mob152]欲望を作成
TheSkyBlock/TheSkyBlock pull request #460
Opened 2021-11-06 01:39 UTC by quikku

2021-12-03 12:53 UTC, ChenCMD requested changes

2021-12-03 12:53 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0152.desire/attack/2.attack.mcfunction
> +    tag @s add AttackThis
thisで良いのでは....？
と、言うかそもそも不要では....？

2021-12-04 13:39 UTC, quikku commented on Asset/data/asset/functions/mob/0152.desire/attack/2.attack.mcfunction
> +    tag @s add AttackThis
48.HasMPを持っていない時に48.HasMPを付与する
48.HasMPを持っている時に48.HasMPを外す
みたいな処理をしてるからthisないと同時に実行されちゃいそうな気もするのん
あとthisはどっかで使ってそうだったから一応除外したけど使っていいのかな

2021-12-13 17:06 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0152.desire/attack/2.attack.mcfunction
> +    tag @s add AttackThis
> 48.HasMPを持っている時に48.HasMPを外す みたいな処理をしてるからthisないと同時に実行されちゃいそうな気もするのん
んー、確かにそういう挙動ではありそう。ただそれならその名前は不適切なのでもうちょいまともな値をつけるべきだと思います

2021-12-15 05:59 UTC, ChenCMD approved these changes

2021-12-15 06:21 UTC, merged