0187& 0188 、ファイアメイジとそのモブ用のProjectieを作成
TheSkyBlock/TheSkyBlock pull request #478
Opened 2021-11-23 12:14 UTC by Chuzume

2021-11-23 13:00 UTC, quikku reviewed
漏れがあるかもなので要確認してくださいのんですわぁ！
基本的にはそのままchange comitすれば良さそうだけどね

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0188.fireball/0.load.mcfunction
> +    scoreboard objectives add Chuz.Recursive dummy
```suggestion
    scoreboard objectives add 58.Range dummy
    scoreboard objectives add 58.Speed dummy
    scoreboard objectives add 58.Recursive dummy
```
36進数にしてほしいのんぜ

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0188.fireball/_index.d.mcfunction
> +    #declare tag 0188.Start
```suggestion
    #declare tag 58.Init
    #declare tag 58.Start
```
10進数ではなく36進数ぞ
スコアの文字数制限なくなったけど一括置換とかしたいだろうし現状は36進数で統一しようのん

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0188.fireball/event/break.mcfunction
> +scoreboard players reset @s Chuz.Range
```suggestion

scoreboard players reset @s 58.Range
```

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0188.fireball/event/hit.mcfunction
> +    #execute store result storage csr_score_damage: ChuzDamage.Head int 1 run data get entity @s data.ChuzData.HeadDamage
特に気にはならんがこれどっかからコピーしてきたものがそのままっぽい？

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0188.fireball/tick/init.mcfunction
> +    scoreboard players set @s Chuz.Speed 4
```suggestion
    scoreboard players set @s 58.Range 100
    scoreboard players set @s 58.Speed 4
```

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0188.fireball/tick/move.mcfunction
> +    execute if entity @s[scores={Chuz.Range=0}] run function asset:mob/0188.fireball/event/break
```suggestion
# 再帰カウントが0なら弾速からセット
    execute unless entity @s[scores={58.Recursive=1..,Chuz.Range=1..}] run scoreboard players operation @s 58.Recursive = @s 58.Speed

# 前進
    execute if entity @s[scores={58.Recursive=1..,58.Range=1..}] run tp @s ^ ^ ^0.25 ~ ~

# スコア減算
    scoreboard players remove @s 58.Recursive 1
    scoreboard players remove @s 58.Range 1

# プレイヤーの衝突判定
    execute positioned ~-0.5 ~0.0 ~-0.5 if entity @p[dx=0] run function asset:mob/0188.fireball/event/hit

# 壁の衝突判定
    execute unless block ~ ~ ~ #lib:no_collision run function asset:mob/0188.fireball/event/hit

# 再帰
    execute if entity @s[scores={58.Recursive=1..,58.Range=1..}] at @s run function asset:mob/0188.fireball/tick/move

# キル
    execute if entity @s[scores={58.Range=0}] run function asset:mob/0188.fireball/event/break
```

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0187.flame_mage/summon/2.summon.mcfunction
> +    data modify storage asset:mob WeaponDropChances set value [0.0f,0.0f]
どうでもいいけどわざわざこれする意味もないのんよね実は
特に修正しなくても良さそうだけど

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0187.flame_mage/tick/2.tick.mcfunction
> +    execute if score @s 0187.Attack matches 40.. run function asset:mob/0187.flame_mage/event/shoot_magic
```suggestion
    execute if score @s 57.Attack matches 40.. run function asset:mob/0187.flame_mage/event/shoot_magic
```

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0187.flame_mage/tick/2.tick.mcfunction
> +    execute if entity @p[distance=..20] run scoreboard players add @s 0187.Attack 1
```suggestion
    execute if entity @p[distance=..20] run scoreboard players add @s 57.Attack 1
```

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0187.flame_mage/tick/2.tick.mcfunction
> +    execute unless entity @p[distance=..20] run scoreboard players reset @s 0187.Attack
```suggestion
    execute unless entity @p[distance=..20] run scoreboard players reset @s 57.Attack
```

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0188.fireball/summon/2.summon.mcfunction
> +    summon marker ~ ~ ~ {Tags:["MobInit","0188.Init"],DeathLootTable:"asset:mob/death/0188.fireball"}
```suggestion
    summon marker ~ ~ ~ {Tags:["MobInit","58.Init"],DeathLootTable:"asset:mob/death/0188.fireball"}
```

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0188.fireball/tick/2.tick.mcfunction
> +    execute if entity @s[tag=0188.Init] run function asset:mob/0188.fireball/tick/init
```suggestion
# 移動
    execute if entity @s[tag=58.Start] run function asset:mob/0188.fireball/tick/move

# Init
    execute if entity @s[tag=58.Init] run function asset:mob/0188.fireball/tick/init
```

2021-11-23 13:00 UTC, quikku commented on Asset/data/asset/functions/mob/0188.fireball/tick/init.mcfunction
> +    tag @s add 0188.Start
```suggestion
    tag @s remove 58.Init
    tag @s add 58.Start
```

2021-12-13 18:24 UTC, ChenCMD requested changes

2021-12-13 18:24 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0188.fireball/event/damage.mcfunction
> +    function lib:damage/modifier
これだとプレイヤーの補正が乗ってしまうので`~/event/hit.mcf`のところで実行するとよいと思います

2021-12-13 18:24 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0188.fireball/event/break.mcfunction
> +scoreboard players reset @s 58.Range
これは別にどちらでもいいけどどうせkillするからresetする必要はないかも

2021-12-13 18:24 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0188.fireball/tick/move.mcfunction
> +    execute unless entity @s[scores={58.Recursive=1..,58.Range=1..}] run scoreboard players operation @s 58.Recursive = @s 58.Speed
このセット、毎tick最初にだけ実行されてる気がするので(間違ってたらごめん)`~/2.tick.mcf`側で処理しちゃったほうが再帰の度に呼ばれないから軽いかも

2021-12-13 18:24 UTC, ChenCMD commented on Asset/data/asset/loot_tables/mob/death/0188.fireball.json
> +{
要らなそう

2021-12-13 18:24 UTC, ChenCMD commented on Asset/data/asset/functions/mob/0188.fireball/summon/2.summon.mcfunction
> +    summon marker ~ ~ ~ {Tags:["MobInit","58.Init"],DeathLootTable:"asset:mob/death/0188.fireball"}
要らなそう
```suggestion
    summon marker ~ ~ ~ {Tags:["MobInit","58.Init"]}
```

2021-12-13 18:47 UTC, ChenCMD approved these changes

2021-12-15 06:58 UTC, merged