革装備セットを作成
TheSkyBlock/TheSkyBlock pull request #48
Opened 2021-01-02 14:13 UTC by quikku

0090番の神器

2021-01-02 16:32 UTC, ChenCMD requested changes

2021-01-02 16:32 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0090.leatherequipmentset/3.main.mcfunction
> +    execute as @s[nbt={Inventory:[{Slot:100b},{Slot:101b},{Slot:102b},{Slot:103b}]}] at @s run playsound minecraft:item.shield.break player @a ~ ~ ~ 1 0.5
ここ、replaceitemの手前に置かないと確定で成功のSEがなりそう

2021-01-02 17:25 UTC, quikku commented on Asset/data/asset/functions/sacred_treasure/0090.leatherequipmentset/3.main.mcfunction
> +    execute as @s[nbt={Inventory:[{Slot:100b},{Slot:101b},{Slot:102b},{Slot:103b}]}] at @s run playsound minecraft:item.shield.break player @a ~ ~ ~ 1 0.5
確定で失敗でした（全部位装着時失敗なので）

2021-01-03 15:01 UTC, ChenCMD approved these changes

2021-01-04 05:13 UTC, merged