ID:0573 ファイナルプリズムの最後(希望)の修正
TheSkyBlock/TheSkyBlock pull request #549
Opened 2021-12-21 21:03 UTC by Chuzume

2021-12-22 09:46 UTC, ChenCMD requested changes
`~/_.give.mcf`の36行目を見るとわかるんですが攻撃情報に防御貫通を載せれるので特に意図して隠してない限りはtrueにしておくといいと思うよ
Opt: PrismDamageタグを付与する場所のセレクター、type引数が付いてるといい感じだと思う

2021-12-22 09:46 UTC, ChenCMD commented on TheSkyBlock/data/minecraft/loot_tables/blocks/lime_shulker_box.json
> +                                    "type": "minecraft:shulker_box",
紛れ込ませちゃダメなやつですこれ

2021-12-22 10:31 UTC, Chuzume commented on TheSkyBlock/data/minecraft/loot_tables/blocks/lime_shulker_box.json
> +                                    "type": "minecraft:shulker_box",
この記述でも1.17にて動作することを確認しました。
将来的に1.18以降に対応するのであれば、今のうちに対応しておいたほうがいいと思われますが。

よろしくお願いします。

2021-12-22 11:27 UTC, ChenCMD commented on TheSkyBlock/data/minecraft/loot_tables/blocks/lime_shulker_box.json
> +                                    "type": "minecraft:shulker_box",
> 将来的に1.18以降に対応するのであれば、今のうちに対応しておいたほうがいい

確かにその通りなのだけど、それをこのPRに含めるのは妥当ではないかな〜みたいな感じです

2021-12-23 08:02 UTC, ChenCMD approved these changes

2021-12-23 08:03 UTC, merged