[神器79] 飛竜落としの術の作成
TheSkyBlock/TheSkyBlock pull request #60
Opened 2021-01-08 05:25 UTC by kaputina

神器ID79 飛竜落としの術を作成しました
サンダーボルトにかなり(ほぼ完全に？)似てしまったので
権利等々問題があれば修正の指示をお願いします

2021-03-06 12:58 UTC, ChenCMD requested changes
つくれるよ

2021-03-06 13:00 UTC, kaputina commented
あれ・・・？
こっちはもうEnemyTagで判別してた気がします

2021-03-06 13:13 UTC, ChenCMD requested changes
type=#lib:livingがついてたりついてなかったりするので統一してね

2021-03-06 13:13 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0079.shoot_down_a_flying_dragon/2.check_condition.mcfunction
> +    execute unless entity @e[type=!player,tag=Enemy,distance=..10] run tag @s remove CanUsed
```suggestion
    execute unless entity @e[tag=Enemy,distance=..10] run tag @s remove CanUsed
```

2021-03-06 13:13 UTC, ChenCMD commented on Asset/data/asset/tags/functions/sacred_treasure/click.carrot_on_a_stick.json
> +        "asset:sacred_treasure/0183.answer_to_the_ultimate_question_of_life_the_universe_and_everything/1.trigger",
```suggestion
```

2021-03-06 13:13 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0079.shoot_down_a_flying_dragon/3.main.mcfunction
> +            execute as @e[type=#lib:living,tag=Hit,distance=..10] at @s run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 10 2
```suggestion
            execute at @e[type=#lib:living,tag=Hit,distance=..10] run particle enchanted_hit ~ ~2 ~ 0.02 5 0.02 0 75 force @a
            execute if score $AttackStrength Temporary matches 0 at @e[type=#lib:living,tag=Hit,distance=..10] run particle dust 0.941 1 0.11 0.5 ~ ~2 ~ 0.02 5 0.02 0 150 force @a
            execute if score $AttackStrength Temporary matches 1 at @e[type=#lib:living,tag=Hit,distance=..10] run particle dust 1 0.69 0.11 0.5 ~ ~2 ~ 0.02 5 0.02 0 150 force @a
            execute if score $AttackStrength Temporary matches 2 at @e[type=#lib:living,tag=Hit,distance=..10] run particle dust 1 0.176 0.176 0.5 ~ ~2 ~ 0.02 5 0.02 0 150 force @a
            execute if score $AttackStrength Temporary matches 3 at @e[type=#lib:living,tag=Hit,distance=..10] run particle dust 0.929 0.137 1 0.5 ~ ~2 ~ 0.02 5 0.02 0 150 force @a
        # Sound
            execute at @e[type=#lib:living,tag=Hit,distance=..10] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 10 2
            execute at @e[type=#lib:living,tag=Hit,distance=..10] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 10 2
            execute at @e[type=#lib:living,tag=Hit,distance=..10] run playsound entity.lightning_bolt.thunder master @a ~ ~ ~ 10 2
```

2021-03-23 10:40 UTC, ChenCMD requested changes

2021-03-23 10:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0079.shoot_down_a_flying_dragon/3.main.mcfunction
> +            execute if score $AroundWater Temporary matches 1.. run scoreboard players add $AttackStrength Temporary 1
キニナル＝インデント

2021-03-23 10:40 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0079.shoot_down_a_flying_dragon/2.check_condition.mcfunction
> +    execute unless entity @e[tag=Enemy,distance=..10] run tag @s remove CanUsed
type引数

2021-03-23 10:57 UTC, kaputina commented on Asset/data/asset/functions/sacred_treasure/0079.shoot_down_a_flying_dragon/3.main.mcfunction
> +            execute if score $AroundWater Temporary matches 1.. run scoreboard players add $AttackStrength Temporary 1
他の人が見た時のコメントとしてのやつは
# //こんな感じ
にしてインデントなし

処理をくくるためのやつは
# こんなかんじ
にして、インデント入れる

って感じにしてたんですが、前者にもインデントは入れた方がいいんですかね･･･？

2021-03-23 11:26 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0079.shoot_down_a_flying_dragon/3.main.mcfunction
> +            execute if score $AroundWater Temporary matches 1.. run scoreboard players add $AttackStrength Temporary 1
その意図が特に全体で共有されてるわけではないから下にそろえたほうが見やすいと思う

2021-03-23 12:23 UTC, kaputina commented on Asset/data/asset/functions/sacred_treasure/0079.shoot_down_a_flying_dragon/3.main.mcfunction
> +            execute if score $AroundWater Temporary matches 1.. run scoreboard players add $AttackStrength Temporary 1
うーん･･･了解です！
下に統一します！
･･･が、コメントみたいなのも付けたい時があるんですよね

2021-03-29 07:48 UTC, ChenCMD approved these changes

2021-03-29 07:49 UTC, merged