魔女に与える鉄槌 Dev/uran2471
TheSkyBlock/TheSkyBlock pull request #62
Opened 2021-01-08 14:32 UTC by uran247

riding mobが剥がれない問題はTP直後killで対応(死亡エフェクト見えちゃうけど)

2021-01-10 15:18 UTC, ChenCMD requested changes
各所に同じtagをdeclareしてるのがみられるので`~/_index.d.mcf`にまとめてほしい
書き方は[このあたり](https://github.com/TheSkyBlock/TheSkyBlock/blob/master/TheSkyBlock/data/asset/functions/sacred_treasure/lib/_index.d.mcfunction)とか参考にしてくだせ

2021-01-10 15:18 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.main.mcfunction
> +    #declare storage data asset:temp
これはなくて大丈夫。
```suggestion
```

2021-01-10 15:18 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.1.flying.mcfunction
> +schedule function asset:sacred_treasure/0035.malleus_maleficarum/3.1.check_hit_manager 1t replace
これ、わざわざfunctionにしなくても2行なら`~/3.1.check_hit_manager.mcf`に統合してよさそう

2021-01-10 15:18 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.2.witchification.mcfunction
> +    execute positioned ~-0.5 ~-0.5 ~-0.5 as @e[tag=MalleusMaleficarumSacrifice,dx=1,dy=1,dz=1,sort=nearest,limit=1] at @s run particle landing_obsidian_tear ~ ~0.1 ~ 0.5 0 0.5 0 500 force
entity一体に付きparticle force 500は多いかも...?

2021-01-11 08:46 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.main.mcfunction
> +    #declare storage data asset:temp
タグの宣言修正済み

2021-01-11 08:47 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.1.flying.mcfunction
> +schedule function asset:sacred_treasure/0035.malleus_maleficarum/3.1.check_hit_manager 1t replace
たとえ1行でもscheduleから呼び出すfunctionに直接処理はかかず、呼び出す処理のみ書いたほうが可読性に貢献する。
そのためこの書き方で残置したい。
一方でスケジュールの再予約は1回でよく、このfunction内に書けばよいため移動。

2021-01-11 08:48 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.2.witchification.mcfunction
> +    execute positioned ~-0.5 ~-0.5 ~-0.5 as @e[tag=MalleusMaleficarumSacrifice,dx=1,dy=1,dz=1,sort=nearest,limit=1] at @s run particle landing_obsidian_tear ~ ~0.1 ~ 0.5 0 0.5 0 500 force
200に削減した

2021-01-11 11:51 UTC, ChenCMD requested changes

2021-01-11 11:51 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.main.mcfunction
> +    execute anchored eyes run summon ender_pearl ^ ^ ^1 {Tags:[MalleusMaleficarumInit,MalleusMaleficarumEntity],Passengers:[{id:"minecraft:armor_stand",Tags:[MalleusMaleficarumIndicator,MalleusMalefi
負荷軽減のため可能であればAECを使ってほしいかな

2021-01-11 11:51 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.main.mcfunction
> +#   asset:sacred_treasure/0035.malleus_maleficarum/3.1.entity_manager
```suggestion
# @within function asset:sacred_treasure/0035.malleus_maleficarum/2.check_condition
```

2021-01-11 11:51 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.entity_manager.mcfunction
> +execute if entity @e[tag=MalleusMaleficarumIndicator,predicate=asset:0035.malleus_maleficarum/is_ride_on_enderpearl] run schedule function asset:sacred_treasure/0035.malleus_maleficarum/3.1.entity_ma
軽量化のためにtype引数を追加してね

2021-01-11 11:51 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.2.witchification.mcfunction
> +    execute positioned ~-0.5 -100 ~-0.5 as @e[tag=MalleusMaleficarumSacrifice,dx=1,dy=1,dz=1,sort=nearest,limit=1] run kill @s
`#lib:living`ってtags/entity_typesがあるのでそれ使ってね

2021-01-11 12:06 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.1.flying.mcfunction
> +#   asset:sacred_treasure/0035.malleus_maleficarum/3.1.entity_manager
修正済み

2021-01-11 12:06 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.2.witchification.mcfunction
> +#   asset:sacred_treasure/0035.malleus_maleficarum/3.1.entity_manager
修正済み

2021-01-11 12:06 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.entity_manager.mcfunction
> +#   asset:sacred_treasure/0035.malleus_maleficarum/3.1.1.flying
修正済み

2021-01-11 12:14 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.main.mcfunction
> +    execute anchored eyes run summon ender_pearl ^ ^ ^1 {Tags:[MalleusMaleficarumInit,MalleusMaleficarumEntity],Passengers:[{id:"minecraft:armor_stand",Tags:[MalleusMaleficarumIndicator,MalleusMalefi
検証したところAECではPassengerが剥がれてしまいロジックが破綻するのでarmor_standのままとしたい。

2021-01-11 12:14 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.main.mcfunction
> +#   asset:sacred_treasure/0035.malleus_maleficarum/3.1.entity_manager
修正済み

2021-01-11 12:14 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.entity_manager.mcfunction
> +execute if entity @e[tag=MalleusMaleficarumIndicator,predicate=asset:0035.malleus_maleficarum/is_ride_on_enderpearl] run schedule function asset:sacred_treasure/0035.malleus_maleficarum/3.1.entity_ma
修正済み

2021-01-11 12:14 UTC, uran247 commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.2.witchification.mcfunction
> +    execute positioned ~-0.5 -100 ~-0.5 as @e[tag=MalleusMaleficarumSacrifice,dx=1,dy=1,dz=1,sort=nearest,limit=1] run kill @s
修正済み

2021-01-12 04:03 UTC, ChenCMD approved these changes

2021-01-12 04:03 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0035.malleus_maleficarum/3.1.entity_manager.mcfunction
> +execute if entity @e[type=armor_stand,tag=MalleusMaleficarumIndicator,predicate=asset:0035.malleus_maleficarum/is_ride_on_enderpearl] run schedule function asset:sacred_treasure/0035.malleus_malefica
```suggestion
#アーマースタンドがエンダーパールの上に乗っていない状態なら命中処理
    execute as @e[type=armor_stand,tag=MalleusMaleficarumIndicator] unless predicate asset:0035.malleus_maleficarum/is_ride_on_enderpearl at @s run function asset:sacred_treasure/0035.malleus_maleficarum/3.1.2.witchification

#アーマースタンドがエンダーパールの上に乗っている状態なら飛翔処理
    execute as @e[type=armor_stand,tag=MalleusMaleficarumIndicator] if predicate asset:0035.malleus_maleficarum/is_ride_on_enderpearl at @s run function asset:sacred_treasure/0035.malleus_maleficarum/3.1.1.flying

# 次tickのmanager実行予約
    execute if entity @e[type=armor_stand,tag=MalleusMaleficarumIndicator,predicate=asset:0035.malleus_maleficarum/is_ride_on_enderpearl] run schedule function asset:sacred_treasure/0035.malleus_maleficarum/3.1.entity_manager 1t replace
```

2021-01-12 04:06 UTC, merged