[神器188] 逆転写魔素の作成
TheSkyBlock/TheSkyBlock pull request #63
Opened 2021-01-09 00:03 UTC by kaputina

2021-01-10 15:44 UTC, ChenCMD requested changes

2021-01-10 15:44 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0188.reverse_transcription_magic/2.check_condition.mcfunction
> +    execute store result score $MPRequire Temporary run data get entity @s Inventory[{Slot:-106b}].tag.TSB.MPRequire
近々参照する方法を作るのでそれまでお待ち下せ

2021-01-10 15:44 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0188.reverse_transcription_magic/3.main.mcfunction
> +    execute store result score $Set Lib run data get entity @s Inventory[{Slot:-106b}].tag.TSB.MPRequire
上と同様

2021-01-10 15:51 UTC, kaputina commented on Asset/data/asset/functions/sacred_treasure/0188.reverse_transcription_magic/2.check_condition.mcfunction
> +    execute store result score $MPRequire Temporary run data get entity @s Inventory[{Slot:-106b}].tag.TSB.MPRequire
わぁい･･･
てかこれってもしかしてstorageから参照できましたかね･･･？

2021-01-10 15:52 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0188.reverse_transcription_magic/2.check_condition.mcfunction
> +    execute store result score $MPRequire Temporary run data get entity @s Inventory[{Slot:-106b}].tag.TSB.MPRequire
できるけどasset側に晒してないstorageだからCoreを調整するかな

2021-01-10 15:53 UTC, kaputina commented on Asset/data/asset/functions/sacred_treasure/0188.reverse_transcription_magic/2.check_condition.mcfunction
> +    execute store result score $MPRequire Temporary run data get entity @s Inventory[{Slot:-106b}].tag.TSB.MPRequire
なるほど。了解です！

2021-02-03 18:41 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0188.reverse_transcription_magic/2.check_condition.mcfunction
> +    execute store result score $MPRequire Temporary run data get entity @s Inventory[{Slot:-106b}].tag.TSB.MPRequire
できるようにしたよ
https://github.com/TheSkyBlock/TheSkyBlock/wiki/create-sacred-treasure#51-storage-assetcontext%E3%81%AB%E5%85%A5%E3%81%A3%E3%81%A6%E3%81%84%E3%82%8B%E6%83%85%E5%A0%B1
を参照してね

2021-02-04 10:16 UTC, ChenCMD requested changes

2021-02-04 10:16 UTC, ChenCMD commented on Asset/data/asset/tags/functions/sacred_treasure/click.carrot_on_a_stick.json
> +        "asset:sacred_treasure/0108.vacuum_hopper/1.trigger",
```suggestion
```

2021-02-04 10:16 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0188.reverse_transcription_magic/3.main.mcfunction
> +    particle totem_of_undying ~ ~1.5 ~ 0.5 1 0.5 0 100 force @s
```suggestion
    # MPをOffhandItemのMPRequireに設定
        execute store result score $Set Lib run data get storage asset:context Items.offhand.tag.TSB.MPRequire
        tellraw @s [{"text": "MPが ["},{"nbt": "Items.offhand.tag.display.Name","entity": "@s","interpret": true},{"text": "] の消費MP [ "},{"score": {"name": "$Set","objective": "Lib"}},{"text": " ] になった！"}]
        function lib:mp/set
    # 演出
        playsound entity.player.levelup master @s ~ ~ ~ 1 1 1
        stopsound @s * entity.item.break
        particle totem_of_undying ~ ~1.5 ~ 0.5 1 0.5 0 100 force @s
```

2021-02-05 15:27 UTC, ChenCMD approved these changes

2021-02-05 15:28 UTC, merged