[神器0122] ルナティック・レイの作成
TheSkyBlock/TheSkyBlock pull request #74
Opened 2021-01-11 04:02 UTC by kaputina

@書いた方 おもってたのと違ったら言ってください
元ネタ調べたらありそうでしたがsheetの情報準拠でやりました

2021-01-11 12:02 UTC, ChenCMD requested changes

2021-01-11 12:02 UTC, ChenCMD commented on Asset/data/asset/functions/sacred_treasure/0122.lunatic_lay/3.main.mcfunction
> +    tag @e[type=#lib:living,type=!player,tag=Hit,distance=..5] remove Hit
インデント、それから全部の引数にlimit=1つけたほうが軽いはず
後、他人からparticle見えないのは想定？

2021-01-11 12:15 UTC, kaputina commented on Asset/data/asset/functions/sacred_treasure/0122.lunatic_lay/3.main.mcfunction
> +    tag @e[type=#lib:living,type=!player,tag=Hit,distance=..5] remove Hit
・インデントの付け方(つける基準？)いまいちわかってないので
どこかにSampleあるとありがたいです(わかりにくい処理の説明ならインデントなし、処理グループとしての指標ならインデント、等)
ちなみに今回は前者的な意味でのコメントだったのでいいかな、と思っちゃいました

・あと、limit=1ってつけた方がいいんですかね
どこかでsortとlimitはnbtの次くらいにコスト高いって聞いた気がしたんですが
付けた方が軽いなら了解です

・particle見えないのは忘れてましたね・・・

2021-01-18 08:22 UTC, ChenCMD approved these changes

2021-01-18 08:23 UTC, merged